package jp.co.aliber.accsystem.entity.auto;

public class CalculationPrice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.calculation_price.calculation_price_id
     *
     * @mbg.generated
     */
    private Long calculationPriceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.calculation_price.calculation_price
     *
     * @mbg.generated
     */
    private Integer calculationPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.calculation_price.hourly_wage_price
     *
     * @mbg.generated
     */
    private Integer hourlyWagePrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.calculation_price.calculation_price_id
     *
     * @return the value of public.calculation_price.calculation_price_id
     *
     * @mbg.generated
     */
    public Long getCalculationPriceId() {
        return calculationPriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.calculation_price.calculation_price_id
     *
     * @param calculationPriceId the value for public.calculation_price.calculation_price_id
     *
     * @mbg.generated
     */
    public void setCalculationPriceId(Long calculationPriceId) {
        this.calculationPriceId = calculationPriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.calculation_price.calculation_price
     *
     * @return the value of public.calculation_price.calculation_price
     *
     * @mbg.generated
     */
    public Integer getCalculationPrice() {
        return calculationPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.calculation_price.calculation_price
     *
     * @param calculationPrice the value for public.calculation_price.calculation_price
     *
     * @mbg.generated
     */
    public void setCalculationPrice(Integer calculationPrice) {
        this.calculationPrice = calculationPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.calculation_price.hourly_wage_price
     *
     * @return the value of public.calculation_price.hourly_wage_price
     *
     * @mbg.generated
     */
    public Integer getHourlyWagePrice() {
        return hourlyWagePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.calculation_price.hourly_wage_price
     *
     * @param hourlyWagePrice the value for public.calculation_price.hourly_wage_price
     *
     * @mbg.generated
     */
    public void setHourlyWagePrice(Integer hourlyWagePrice) {
        this.hourlyWagePrice = hourlyWagePrice;
    }
}