package jp.co.aliber.accsystem.entity.auto;

import java.util.ArrayList;
import java.util.List;

public class CompanyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.company
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.company
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.company
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.company
     *
     * @mbg.generated
     */
    public CompanyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.company
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.company
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.company
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.company
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.company
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.company
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.company
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.company
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.company
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.company
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.company
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCompIdIsNull() {
            addCriterion("comp_id is null");
            return (Criteria) this;
        }

        public Criteria andCompIdIsNotNull() {
            addCriterion("comp_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompIdEqualTo(Long value) {
            addCriterion("comp_id =", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdNotEqualTo(Long value) {
            addCriterion("comp_id <>", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdGreaterThan(Long value) {
            addCriterion("comp_id >", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdGreaterThanOrEqualTo(Long value) {
            addCriterion("comp_id >=", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdLessThan(Long value) {
            addCriterion("comp_id <", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdLessThanOrEqualTo(Long value) {
            addCriterion("comp_id <=", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdIn(List<Long> values) {
            addCriterion("comp_id in", values, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdNotIn(List<Long> values) {
            addCriterion("comp_id not in", values, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdBetween(Long value1, Long value2) {
            addCriterion("comp_id between", value1, value2, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdNotBetween(Long value1, Long value2) {
            addCriterion("comp_id not between", value1, value2, "compId");
            return (Criteria) this;
        }

        public Criteria andCompNameIsNull() {
            addCriterion("comp_name is null");
            return (Criteria) this;
        }

        public Criteria andCompNameIsNotNull() {
            addCriterion("comp_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompNameEqualTo(String value) {
            addCriterion("comp_name =", value, "compName");
            return (Criteria) this;
        }

        public Criteria andCompNameNotEqualTo(String value) {
            addCriterion("comp_name <>", value, "compName");
            return (Criteria) this;
        }

        public Criteria andCompNameGreaterThan(String value) {
            addCriterion("comp_name >", value, "compName");
            return (Criteria) this;
        }

        public Criteria andCompNameGreaterThanOrEqualTo(String value) {
            addCriterion("comp_name >=", value, "compName");
            return (Criteria) this;
        }

        public Criteria andCompNameLessThan(String value) {
            addCriterion("comp_name <", value, "compName");
            return (Criteria) this;
        }

        public Criteria andCompNameLessThanOrEqualTo(String value) {
            addCriterion("comp_name <=", value, "compName");
            return (Criteria) this;
        }

        public Criteria andCompNameLike(String value) {
            addCriterion("comp_name like", value, "compName");
            return (Criteria) this;
        }

        public Criteria andCompNameNotLike(String value) {
            addCriterion("comp_name not like", value, "compName");
            return (Criteria) this;
        }

        public Criteria andCompNameIn(List<String> values) {
            addCriterion("comp_name in", values, "compName");
            return (Criteria) this;
        }

        public Criteria andCompNameNotIn(List<String> values) {
            addCriterion("comp_name not in", values, "compName");
            return (Criteria) this;
        }

        public Criteria andCompNameBetween(String value1, String value2) {
            addCriterion("comp_name between", value1, value2, "compName");
            return (Criteria) this;
        }

        public Criteria andCompNameNotBetween(String value1, String value2) {
            addCriterion("comp_name not between", value1, value2, "compName");
            return (Criteria) this;
        }

        public Criteria andCompKanaIsNull() {
            addCriterion("comp_kana is null");
            return (Criteria) this;
        }

        public Criteria andCompKanaIsNotNull() {
            addCriterion("comp_kana is not null");
            return (Criteria) this;
        }

        public Criteria andCompKanaEqualTo(String value) {
            addCriterion("comp_kana =", value, "compKana");
            return (Criteria) this;
        }

        public Criteria andCompKanaNotEqualTo(String value) {
            addCriterion("comp_kana <>", value, "compKana");
            return (Criteria) this;
        }

        public Criteria andCompKanaGreaterThan(String value) {
            addCriterion("comp_kana >", value, "compKana");
            return (Criteria) this;
        }

        public Criteria andCompKanaGreaterThanOrEqualTo(String value) {
            addCriterion("comp_kana >=", value, "compKana");
            return (Criteria) this;
        }

        public Criteria andCompKanaLessThan(String value) {
            addCriterion("comp_kana <", value, "compKana");
            return (Criteria) this;
        }

        public Criteria andCompKanaLessThanOrEqualTo(String value) {
            addCriterion("comp_kana <=", value, "compKana");
            return (Criteria) this;
        }

        public Criteria andCompKanaLike(String value) {
            addCriterion("comp_kana like", value, "compKana");
            return (Criteria) this;
        }

        public Criteria andCompKanaNotLike(String value) {
            addCriterion("comp_kana not like", value, "compKana");
            return (Criteria) this;
        }

        public Criteria andCompKanaIn(List<String> values) {
            addCriterion("comp_kana in", values, "compKana");
            return (Criteria) this;
        }

        public Criteria andCompKanaNotIn(List<String> values) {
            addCriterion("comp_kana not in", values, "compKana");
            return (Criteria) this;
        }

        public Criteria andCompKanaBetween(String value1, String value2) {
            addCriterion("comp_kana between", value1, value2, "compKana");
            return (Criteria) this;
        }

        public Criteria andCompKanaNotBetween(String value1, String value2) {
            addCriterion("comp_kana not between", value1, value2, "compKana");
            return (Criteria) this;
        }

        public Criteria andCompZipIsNull() {
            addCriterion("comp_zip is null");
            return (Criteria) this;
        }

        public Criteria andCompZipIsNotNull() {
            addCriterion("comp_zip is not null");
            return (Criteria) this;
        }

        public Criteria andCompZipEqualTo(String value) {
            addCriterion("comp_zip =", value, "compZip");
            return (Criteria) this;
        }

        public Criteria andCompZipNotEqualTo(String value) {
            addCriterion("comp_zip <>", value, "compZip");
            return (Criteria) this;
        }

        public Criteria andCompZipGreaterThan(String value) {
            addCriterion("comp_zip >", value, "compZip");
            return (Criteria) this;
        }

        public Criteria andCompZipGreaterThanOrEqualTo(String value) {
            addCriterion("comp_zip >=", value, "compZip");
            return (Criteria) this;
        }

        public Criteria andCompZipLessThan(String value) {
            addCriterion("comp_zip <", value, "compZip");
            return (Criteria) this;
        }

        public Criteria andCompZipLessThanOrEqualTo(String value) {
            addCriterion("comp_zip <=", value, "compZip");
            return (Criteria) this;
        }

        public Criteria andCompZipLike(String value) {
            addCriterion("comp_zip like", value, "compZip");
            return (Criteria) this;
        }

        public Criteria andCompZipNotLike(String value) {
            addCriterion("comp_zip not like", value, "compZip");
            return (Criteria) this;
        }

        public Criteria andCompZipIn(List<String> values) {
            addCriterion("comp_zip in", values, "compZip");
            return (Criteria) this;
        }

        public Criteria andCompZipNotIn(List<String> values) {
            addCriterion("comp_zip not in", values, "compZip");
            return (Criteria) this;
        }

        public Criteria andCompZipBetween(String value1, String value2) {
            addCriterion("comp_zip between", value1, value2, "compZip");
            return (Criteria) this;
        }

        public Criteria andCompZipNotBetween(String value1, String value2) {
            addCriterion("comp_zip not between", value1, value2, "compZip");
            return (Criteria) this;
        }

        public Criteria andCompAdd1IsNull() {
            addCriterion("comp_add1 is null");
            return (Criteria) this;
        }

        public Criteria andCompAdd1IsNotNull() {
            addCriterion("comp_add1 is not null");
            return (Criteria) this;
        }

        public Criteria andCompAdd1EqualTo(String value) {
            addCriterion("comp_add1 =", value, "compAdd1");
            return (Criteria) this;
        }

        public Criteria andCompAdd1NotEqualTo(String value) {
            addCriterion("comp_add1 <>", value, "compAdd1");
            return (Criteria) this;
        }

        public Criteria andCompAdd1GreaterThan(String value) {
            addCriterion("comp_add1 >", value, "compAdd1");
            return (Criteria) this;
        }

        public Criteria andCompAdd1GreaterThanOrEqualTo(String value) {
            addCriterion("comp_add1 >=", value, "compAdd1");
            return (Criteria) this;
        }

        public Criteria andCompAdd1LessThan(String value) {
            addCriterion("comp_add1 <", value, "compAdd1");
            return (Criteria) this;
        }

        public Criteria andCompAdd1LessThanOrEqualTo(String value) {
            addCriterion("comp_add1 <=", value, "compAdd1");
            return (Criteria) this;
        }

        public Criteria andCompAdd1Like(String value) {
            addCriterion("comp_add1 like", value, "compAdd1");
            return (Criteria) this;
        }

        public Criteria andCompAdd1NotLike(String value) {
            addCriterion("comp_add1 not like", value, "compAdd1");
            return (Criteria) this;
        }

        public Criteria andCompAdd1In(List<String> values) {
            addCriterion("comp_add1 in", values, "compAdd1");
            return (Criteria) this;
        }

        public Criteria andCompAdd1NotIn(List<String> values) {
            addCriterion("comp_add1 not in", values, "compAdd1");
            return (Criteria) this;
        }

        public Criteria andCompAdd1Between(String value1, String value2) {
            addCriterion("comp_add1 between", value1, value2, "compAdd1");
            return (Criteria) this;
        }

        public Criteria andCompAdd1NotBetween(String value1, String value2) {
            addCriterion("comp_add1 not between", value1, value2, "compAdd1");
            return (Criteria) this;
        }

        public Criteria andCompAdd2IsNull() {
            addCriterion("comp_add2 is null");
            return (Criteria) this;
        }

        public Criteria andCompAdd2IsNotNull() {
            addCriterion("comp_add2 is not null");
            return (Criteria) this;
        }

        public Criteria andCompAdd2EqualTo(String value) {
            addCriterion("comp_add2 =", value, "compAdd2");
            return (Criteria) this;
        }

        public Criteria andCompAdd2NotEqualTo(String value) {
            addCriterion("comp_add2 <>", value, "compAdd2");
            return (Criteria) this;
        }

        public Criteria andCompAdd2GreaterThan(String value) {
            addCriterion("comp_add2 >", value, "compAdd2");
            return (Criteria) this;
        }

        public Criteria andCompAdd2GreaterThanOrEqualTo(String value) {
            addCriterion("comp_add2 >=", value, "compAdd2");
            return (Criteria) this;
        }

        public Criteria andCompAdd2LessThan(String value) {
            addCriterion("comp_add2 <", value, "compAdd2");
            return (Criteria) this;
        }

        public Criteria andCompAdd2LessThanOrEqualTo(String value) {
            addCriterion("comp_add2 <=", value, "compAdd2");
            return (Criteria) this;
        }

        public Criteria andCompAdd2Like(String value) {
            addCriterion("comp_add2 like", value, "compAdd2");
            return (Criteria) this;
        }

        public Criteria andCompAdd2NotLike(String value) {
            addCriterion("comp_add2 not like", value, "compAdd2");
            return (Criteria) this;
        }

        public Criteria andCompAdd2In(List<String> values) {
            addCriterion("comp_add2 in", values, "compAdd2");
            return (Criteria) this;
        }

        public Criteria andCompAdd2NotIn(List<String> values) {
            addCriterion("comp_add2 not in", values, "compAdd2");
            return (Criteria) this;
        }

        public Criteria andCompAdd2Between(String value1, String value2) {
            addCriterion("comp_add2 between", value1, value2, "compAdd2");
            return (Criteria) this;
        }

        public Criteria andCompAdd2NotBetween(String value1, String value2) {
            addCriterion("comp_add2 not between", value1, value2, "compAdd2");
            return (Criteria) this;
        }

        public Criteria andCompAdd1KanaIsNull() {
            addCriterion("comp_add1_kana is null");
            return (Criteria) this;
        }

        public Criteria andCompAdd1KanaIsNotNull() {
            addCriterion("comp_add1_kana is not null");
            return (Criteria) this;
        }

        public Criteria andCompAdd1KanaEqualTo(String value) {
            addCriterion("comp_add1_kana =", value, "compAdd1Kana");
            return (Criteria) this;
        }

        public Criteria andCompAdd1KanaNotEqualTo(String value) {
            addCriterion("comp_add1_kana <>", value, "compAdd1Kana");
            return (Criteria) this;
        }

        public Criteria andCompAdd1KanaGreaterThan(String value) {
            addCriterion("comp_add1_kana >", value, "compAdd1Kana");
            return (Criteria) this;
        }

        public Criteria andCompAdd1KanaGreaterThanOrEqualTo(String value) {
            addCriterion("comp_add1_kana >=", value, "compAdd1Kana");
            return (Criteria) this;
        }

        public Criteria andCompAdd1KanaLessThan(String value) {
            addCriterion("comp_add1_kana <", value, "compAdd1Kana");
            return (Criteria) this;
        }

        public Criteria andCompAdd1KanaLessThanOrEqualTo(String value) {
            addCriterion("comp_add1_kana <=", value, "compAdd1Kana");
            return (Criteria) this;
        }

        public Criteria andCompAdd1KanaLike(String value) {
            addCriterion("comp_add1_kana like", value, "compAdd1Kana");
            return (Criteria) this;
        }

        public Criteria andCompAdd1KanaNotLike(String value) {
            addCriterion("comp_add1_kana not like", value, "compAdd1Kana");
            return (Criteria) this;
        }

        public Criteria andCompAdd1KanaIn(List<String> values) {
            addCriterion("comp_add1_kana in", values, "compAdd1Kana");
            return (Criteria) this;
        }

        public Criteria andCompAdd1KanaNotIn(List<String> values) {
            addCriterion("comp_add1_kana not in", values, "compAdd1Kana");
            return (Criteria) this;
        }

        public Criteria andCompAdd1KanaBetween(String value1, String value2) {
            addCriterion("comp_add1_kana between", value1, value2, "compAdd1Kana");
            return (Criteria) this;
        }

        public Criteria andCompAdd1KanaNotBetween(String value1, String value2) {
            addCriterion("comp_add1_kana not between", value1, value2, "compAdd1Kana");
            return (Criteria) this;
        }

        public Criteria andCompAdd2KanaIsNull() {
            addCriterion("comp_add2_kana is null");
            return (Criteria) this;
        }

        public Criteria andCompAdd2KanaIsNotNull() {
            addCriterion("comp_add2_kana is not null");
            return (Criteria) this;
        }

        public Criteria andCompAdd2KanaEqualTo(String value) {
            addCriterion("comp_add2_kana =", value, "compAdd2Kana");
            return (Criteria) this;
        }

        public Criteria andCompAdd2KanaNotEqualTo(String value) {
            addCriterion("comp_add2_kana <>", value, "compAdd2Kana");
            return (Criteria) this;
        }

        public Criteria andCompAdd2KanaGreaterThan(String value) {
            addCriterion("comp_add2_kana >", value, "compAdd2Kana");
            return (Criteria) this;
        }

        public Criteria andCompAdd2KanaGreaterThanOrEqualTo(String value) {
            addCriterion("comp_add2_kana >=", value, "compAdd2Kana");
            return (Criteria) this;
        }

        public Criteria andCompAdd2KanaLessThan(String value) {
            addCriterion("comp_add2_kana <", value, "compAdd2Kana");
            return (Criteria) this;
        }

        public Criteria andCompAdd2KanaLessThanOrEqualTo(String value) {
            addCriterion("comp_add2_kana <=", value, "compAdd2Kana");
            return (Criteria) this;
        }

        public Criteria andCompAdd2KanaLike(String value) {
            addCriterion("comp_add2_kana like", value, "compAdd2Kana");
            return (Criteria) this;
        }

        public Criteria andCompAdd2KanaNotLike(String value) {
            addCriterion("comp_add2_kana not like", value, "compAdd2Kana");
            return (Criteria) this;
        }

        public Criteria andCompAdd2KanaIn(List<String> values) {
            addCriterion("comp_add2_kana in", values, "compAdd2Kana");
            return (Criteria) this;
        }

        public Criteria andCompAdd2KanaNotIn(List<String> values) {
            addCriterion("comp_add2_kana not in", values, "compAdd2Kana");
            return (Criteria) this;
        }

        public Criteria andCompAdd2KanaBetween(String value1, String value2) {
            addCriterion("comp_add2_kana between", value1, value2, "compAdd2Kana");
            return (Criteria) this;
        }

        public Criteria andCompAdd2KanaNotBetween(String value1, String value2) {
            addCriterion("comp_add2_kana not between", value1, value2, "compAdd2Kana");
            return (Criteria) this;
        }

        public Criteria andCompTelIsNull() {
            addCriterion("comp_tel is null");
            return (Criteria) this;
        }

        public Criteria andCompTelIsNotNull() {
            addCriterion("comp_tel is not null");
            return (Criteria) this;
        }

        public Criteria andCompTelEqualTo(String value) {
            addCriterion("comp_tel =", value, "compTel");
            return (Criteria) this;
        }

        public Criteria andCompTelNotEqualTo(String value) {
            addCriterion("comp_tel <>", value, "compTel");
            return (Criteria) this;
        }

        public Criteria andCompTelGreaterThan(String value) {
            addCriterion("comp_tel >", value, "compTel");
            return (Criteria) this;
        }

        public Criteria andCompTelGreaterThanOrEqualTo(String value) {
            addCriterion("comp_tel >=", value, "compTel");
            return (Criteria) this;
        }

        public Criteria andCompTelLessThan(String value) {
            addCriterion("comp_tel <", value, "compTel");
            return (Criteria) this;
        }

        public Criteria andCompTelLessThanOrEqualTo(String value) {
            addCriterion("comp_tel <=", value, "compTel");
            return (Criteria) this;
        }

        public Criteria andCompTelLike(String value) {
            addCriterion("comp_tel like", value, "compTel");
            return (Criteria) this;
        }

        public Criteria andCompTelNotLike(String value) {
            addCriterion("comp_tel not like", value, "compTel");
            return (Criteria) this;
        }

        public Criteria andCompTelIn(List<String> values) {
            addCriterion("comp_tel in", values, "compTel");
            return (Criteria) this;
        }

        public Criteria andCompTelNotIn(List<String> values) {
            addCriterion("comp_tel not in", values, "compTel");
            return (Criteria) this;
        }

        public Criteria andCompTelBetween(String value1, String value2) {
            addCriterion("comp_tel between", value1, value2, "compTel");
            return (Criteria) this;
        }

        public Criteria andCompTelNotBetween(String value1, String value2) {
            addCriterion("comp_tel not between", value1, value2, "compTel");
            return (Criteria) this;
        }

        public Criteria andClassificationIsNull() {
            addCriterion("classification is null");
            return (Criteria) this;
        }

        public Criteria andClassificationIsNotNull() {
            addCriterion("classification is not null");
            return (Criteria) this;
        }

        public Criteria andClassificationEqualTo(Integer value) {
            addCriterion("classification =", value, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationNotEqualTo(Integer value) {
            addCriterion("classification <>", value, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationGreaterThan(Integer value) {
            addCriterion("classification >", value, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationGreaterThanOrEqualTo(Integer value) {
            addCriterion("classification >=", value, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationLessThan(Integer value) {
            addCriterion("classification <", value, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationLessThanOrEqualTo(Integer value) {
            addCriterion("classification <=", value, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationIn(List<Integer> values) {
            addCriterion("classification in", values, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationNotIn(List<Integer> values) {
            addCriterion("classification not in", values, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationBetween(Integer value1, Integer value2) {
            addCriterion("classification between", value1, value2, "classification");
            return (Criteria) this;
        }

        public Criteria andClassificationNotBetween(Integer value1, Integer value2) {
            addCriterion("classification not between", value1, value2, "classification");
            return (Criteria) this;
        }

        public Criteria andCorporationIdIsNull() {
            addCriterion("corporation_id is null");
            return (Criteria) this;
        }

        public Criteria andCorporationIdIsNotNull() {
            addCriterion("corporation_id is not null");
            return (Criteria) this;
        }

        public Criteria andCorporationIdEqualTo(Long value) {
            addCriterion("corporation_id =", value, "corporationId");
            return (Criteria) this;
        }

        public Criteria andCorporationIdNotEqualTo(Long value) {
            addCriterion("corporation_id <>", value, "corporationId");
            return (Criteria) this;
        }

        public Criteria andCorporationIdGreaterThan(Long value) {
            addCriterion("corporation_id >", value, "corporationId");
            return (Criteria) this;
        }

        public Criteria andCorporationIdGreaterThanOrEqualTo(Long value) {
            addCriterion("corporation_id >=", value, "corporationId");
            return (Criteria) this;
        }

        public Criteria andCorporationIdLessThan(Long value) {
            addCriterion("corporation_id <", value, "corporationId");
            return (Criteria) this;
        }

        public Criteria andCorporationIdLessThanOrEqualTo(Long value) {
            addCriterion("corporation_id <=", value, "corporationId");
            return (Criteria) this;
        }

        public Criteria andCorporationIdIn(List<Long> values) {
            addCriterion("corporation_id in", values, "corporationId");
            return (Criteria) this;
        }

        public Criteria andCorporationIdNotIn(List<Long> values) {
            addCriterion("corporation_id not in", values, "corporationId");
            return (Criteria) this;
        }

        public Criteria andCorporationIdBetween(Long value1, Long value2) {
            addCriterion("corporation_id between", value1, value2, "corporationId");
            return (Criteria) this;
        }

        public Criteria andCorporationIdNotBetween(Long value1, Long value2) {
            addCriterion("corporation_id not between", value1, value2, "corporationId");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameIsNull() {
            addCriterion("corp_owner_name is null");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameIsNotNull() {
            addCriterion("corp_owner_name is not null");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameEqualTo(String value) {
            addCriterion("corp_owner_name =", value, "corpOwnerName");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameNotEqualTo(String value) {
            addCriterion("corp_owner_name <>", value, "corpOwnerName");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameGreaterThan(String value) {
            addCriterion("corp_owner_name >", value, "corpOwnerName");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameGreaterThanOrEqualTo(String value) {
            addCriterion("corp_owner_name >=", value, "corpOwnerName");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameLessThan(String value) {
            addCriterion("corp_owner_name <", value, "corpOwnerName");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameLessThanOrEqualTo(String value) {
            addCriterion("corp_owner_name <=", value, "corpOwnerName");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameLike(String value) {
            addCriterion("corp_owner_name like", value, "corpOwnerName");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameNotLike(String value) {
            addCriterion("corp_owner_name not like", value, "corpOwnerName");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameIn(List<String> values) {
            addCriterion("corp_owner_name in", values, "corpOwnerName");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameNotIn(List<String> values) {
            addCriterion("corp_owner_name not in", values, "corpOwnerName");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameBetween(String value1, String value2) {
            addCriterion("corp_owner_name between", value1, value2, "corpOwnerName");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameNotBetween(String value1, String value2) {
            addCriterion("corp_owner_name not between", value1, value2, "corpOwnerName");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameKanaIsNull() {
            addCriterion("corp_owner_name_kana is null");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameKanaIsNotNull() {
            addCriterion("corp_owner_name_kana is not null");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameKanaEqualTo(String value) {
            addCriterion("corp_owner_name_kana =", value, "corpOwnerNameKana");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameKanaNotEqualTo(String value) {
            addCriterion("corp_owner_name_kana <>", value, "corpOwnerNameKana");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameKanaGreaterThan(String value) {
            addCriterion("corp_owner_name_kana >", value, "corpOwnerNameKana");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameKanaGreaterThanOrEqualTo(String value) {
            addCriterion("corp_owner_name_kana >=", value, "corpOwnerNameKana");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameKanaLessThan(String value) {
            addCriterion("corp_owner_name_kana <", value, "corpOwnerNameKana");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameKanaLessThanOrEqualTo(String value) {
            addCriterion("corp_owner_name_kana <=", value, "corpOwnerNameKana");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameKanaLike(String value) {
            addCriterion("corp_owner_name_kana like", value, "corpOwnerNameKana");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameKanaNotLike(String value) {
            addCriterion("corp_owner_name_kana not like", value, "corpOwnerNameKana");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameKanaIn(List<String> values) {
            addCriterion("corp_owner_name_kana in", values, "corpOwnerNameKana");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameKanaNotIn(List<String> values) {
            addCriterion("corp_owner_name_kana not in", values, "corpOwnerNameKana");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameKanaBetween(String value1, String value2) {
            addCriterion("corp_owner_name_kana between", value1, value2, "corpOwnerNameKana");
            return (Criteria) this;
        }

        public Criteria andCorpOwnerNameKanaNotBetween(String value1, String value2) {
            addCriterion("corp_owner_name_kana not between", value1, value2, "corpOwnerNameKana");
            return (Criteria) this;
        }

        public Criteria andCorpSortNoIsNull() {
            addCriterion("corp_sort_no is null");
            return (Criteria) this;
        }

        public Criteria andCorpSortNoIsNotNull() {
            addCriterion("corp_sort_no is not null");
            return (Criteria) this;
        }

        public Criteria andCorpSortNoEqualTo(String value) {
            addCriterion("corp_sort_no =", value, "corpSortNo");
            return (Criteria) this;
        }

        public Criteria andCorpSortNoNotEqualTo(String value) {
            addCriterion("corp_sort_no <>", value, "corpSortNo");
            return (Criteria) this;
        }

        public Criteria andCorpSortNoGreaterThan(String value) {
            addCriterion("corp_sort_no >", value, "corpSortNo");
            return (Criteria) this;
        }

        public Criteria andCorpSortNoGreaterThanOrEqualTo(String value) {
            addCriterion("corp_sort_no >=", value, "corpSortNo");
            return (Criteria) this;
        }

        public Criteria andCorpSortNoLessThan(String value) {
            addCriterion("corp_sort_no <", value, "corpSortNo");
            return (Criteria) this;
        }

        public Criteria andCorpSortNoLessThanOrEqualTo(String value) {
            addCriterion("corp_sort_no <=", value, "corpSortNo");
            return (Criteria) this;
        }

        public Criteria andCorpSortNoLike(String value) {
            addCriterion("corp_sort_no like", value, "corpSortNo");
            return (Criteria) this;
        }

        public Criteria andCorpSortNoNotLike(String value) {
            addCriterion("corp_sort_no not like", value, "corpSortNo");
            return (Criteria) this;
        }

        public Criteria andCorpSortNoIn(List<String> values) {
            addCriterion("corp_sort_no in", values, "corpSortNo");
            return (Criteria) this;
        }

        public Criteria andCorpSortNoNotIn(List<String> values) {
            addCriterion("corp_sort_no not in", values, "corpSortNo");
            return (Criteria) this;
        }

        public Criteria andCorpSortNoBetween(String value1, String value2) {
            addCriterion("corp_sort_no between", value1, value2, "corpSortNo");
            return (Criteria) this;
        }

        public Criteria andCorpSortNoNotBetween(String value1, String value2) {
            addCriterion("corp_sort_no not between", value1, value2, "corpSortNo");
            return (Criteria) this;
        }

        public Criteria andCorpNoIsNull() {
            addCriterion("corp_no is null");
            return (Criteria) this;
        }

        public Criteria andCorpNoIsNotNull() {
            addCriterion("corp_no is not null");
            return (Criteria) this;
        }

        public Criteria andCorpNoEqualTo(Long value) {
            addCriterion("corp_no =", value, "corpNo");
            return (Criteria) this;
        }

        public Criteria andCorpNoNotEqualTo(Long value) {
            addCriterion("corp_no <>", value, "corpNo");
            return (Criteria) this;
        }

        public Criteria andCorpNoGreaterThan(Long value) {
            addCriterion("corp_no >", value, "corpNo");
            return (Criteria) this;
        }

        public Criteria andCorpNoGreaterThanOrEqualTo(Long value) {
            addCriterion("corp_no >=", value, "corpNo");
            return (Criteria) this;
        }

        public Criteria andCorpNoLessThan(Long value) {
            addCriterion("corp_no <", value, "corpNo");
            return (Criteria) this;
        }

        public Criteria andCorpNoLessThanOrEqualTo(Long value) {
            addCriterion("corp_no <=", value, "corpNo");
            return (Criteria) this;
        }

        public Criteria andCorpNoIn(List<Long> values) {
            addCriterion("corp_no in", values, "corpNo");
            return (Criteria) this;
        }

        public Criteria andCorpNoNotIn(List<Long> values) {
            addCriterion("corp_no not in", values, "corpNo");
            return (Criteria) this;
        }

        public Criteria andCorpNoBetween(Long value1, Long value2) {
            addCriterion("corp_no between", value1, value2, "corpNo");
            return (Criteria) this;
        }

        public Criteria andCorpNoNotBetween(Long value1, Long value2) {
            addCriterion("corp_no not between", value1, value2, "corpNo");
            return (Criteria) this;
        }

        public Criteria andCorpKindIsNull() {
            addCriterion("corp_kind is null");
            return (Criteria) this;
        }

        public Criteria andCorpKindIsNotNull() {
            addCriterion("corp_kind is not null");
            return (Criteria) this;
        }

        public Criteria andCorpKindEqualTo(String value) {
            addCriterion("corp_kind =", value, "corpKind");
            return (Criteria) this;
        }

        public Criteria andCorpKindNotEqualTo(String value) {
            addCriterion("corp_kind <>", value, "corpKind");
            return (Criteria) this;
        }

        public Criteria andCorpKindGreaterThan(String value) {
            addCriterion("corp_kind >", value, "corpKind");
            return (Criteria) this;
        }

        public Criteria andCorpKindGreaterThanOrEqualTo(String value) {
            addCriterion("corp_kind >=", value, "corpKind");
            return (Criteria) this;
        }

        public Criteria andCorpKindLessThan(String value) {
            addCriterion("corp_kind <", value, "corpKind");
            return (Criteria) this;
        }

        public Criteria andCorpKindLessThanOrEqualTo(String value) {
            addCriterion("corp_kind <=", value, "corpKind");
            return (Criteria) this;
        }

        public Criteria andCorpKindLike(String value) {
            addCriterion("corp_kind like", value, "corpKind");
            return (Criteria) this;
        }

        public Criteria andCorpKindNotLike(String value) {
            addCriterion("corp_kind not like", value, "corpKind");
            return (Criteria) this;
        }

        public Criteria andCorpKindIn(List<String> values) {
            addCriterion("corp_kind in", values, "corpKind");
            return (Criteria) this;
        }

        public Criteria andCorpKindNotIn(List<String> values) {
            addCriterion("corp_kind not in", values, "corpKind");
            return (Criteria) this;
        }

        public Criteria andCorpKindBetween(String value1, String value2) {
            addCriterion("corp_kind between", value1, value2, "corpKind");
            return (Criteria) this;
        }

        public Criteria andCorpKindNotBetween(String value1, String value2) {
            addCriterion("corp_kind not between", value1, value2, "corpKind");
            return (Criteria) this;
        }

        public Criteria andDeadlineDayIsNull() {
            addCriterion("deadline_day is null");
            return (Criteria) this;
        }

        public Criteria andDeadlineDayIsNotNull() {
            addCriterion("deadline_day is not null");
            return (Criteria) this;
        }

        public Criteria andDeadlineDayEqualTo(Boolean value) {
            addCriterion("deadline_day =", value, "deadlineDay");
            return (Criteria) this;
        }

        public Criteria andDeadlineDayNotEqualTo(Boolean value) {
            addCriterion("deadline_day <>", value, "deadlineDay");
            return (Criteria) this;
        }

        public Criteria andDeadlineDayGreaterThan(Boolean value) {
            addCriterion("deadline_day >", value, "deadlineDay");
            return (Criteria) this;
        }

        public Criteria andDeadlineDayGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deadline_day >=", value, "deadlineDay");
            return (Criteria) this;
        }

        public Criteria andDeadlineDayLessThan(Boolean value) {
            addCriterion("deadline_day <", value, "deadlineDay");
            return (Criteria) this;
        }

        public Criteria andDeadlineDayLessThanOrEqualTo(Boolean value) {
            addCriterion("deadline_day <=", value, "deadlineDay");
            return (Criteria) this;
        }

        public Criteria andDeadlineDayIn(List<Boolean> values) {
            addCriterion("deadline_day in", values, "deadlineDay");
            return (Criteria) this;
        }

        public Criteria andDeadlineDayNotIn(List<Boolean> values) {
            addCriterion("deadline_day not in", values, "deadlineDay");
            return (Criteria) this;
        }

        public Criteria andDeadlineDayBetween(Boolean value1, Boolean value2) {
            addCriterion("deadline_day between", value1, value2, "deadlineDay");
            return (Criteria) this;
        }

        public Criteria andDeadlineDayNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deadline_day not between", value1, value2, "deadlineDay");
            return (Criteria) this;
        }

        public Criteria andDeadlineAdjustDaysIsNull() {
            addCriterion("deadline_adjust_days is null");
            return (Criteria) this;
        }

        public Criteria andDeadlineAdjustDaysIsNotNull() {
            addCriterion("deadline_adjust_days is not null");
            return (Criteria) this;
        }

        public Criteria andDeadlineAdjustDaysEqualTo(Integer value) {
            addCriterion("deadline_adjust_days =", value, "deadlineAdjustDays");
            return (Criteria) this;
        }

        public Criteria andDeadlineAdjustDaysNotEqualTo(Integer value) {
            addCriterion("deadline_adjust_days <>", value, "deadlineAdjustDays");
            return (Criteria) this;
        }

        public Criteria andDeadlineAdjustDaysGreaterThan(Integer value) {
            addCriterion("deadline_adjust_days >", value, "deadlineAdjustDays");
            return (Criteria) this;
        }

        public Criteria andDeadlineAdjustDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("deadline_adjust_days >=", value, "deadlineAdjustDays");
            return (Criteria) this;
        }

        public Criteria andDeadlineAdjustDaysLessThan(Integer value) {
            addCriterion("deadline_adjust_days <", value, "deadlineAdjustDays");
            return (Criteria) this;
        }

        public Criteria andDeadlineAdjustDaysLessThanOrEqualTo(Integer value) {
            addCriterion("deadline_adjust_days <=", value, "deadlineAdjustDays");
            return (Criteria) this;
        }

        public Criteria andDeadlineAdjustDaysIn(List<Integer> values) {
            addCriterion("deadline_adjust_days in", values, "deadlineAdjustDays");
            return (Criteria) this;
        }

        public Criteria andDeadlineAdjustDaysNotIn(List<Integer> values) {
            addCriterion("deadline_adjust_days not in", values, "deadlineAdjustDays");
            return (Criteria) this;
        }

        public Criteria andDeadlineAdjustDaysBetween(Integer value1, Integer value2) {
            addCriterion("deadline_adjust_days between", value1, value2, "deadlineAdjustDays");
            return (Criteria) this;
        }

        public Criteria andDeadlineAdjustDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("deadline_adjust_days not between", value1, value2, "deadlineAdjustDays");
            return (Criteria) this;
        }

        public Criteria andPaymentDayIsNull() {
            addCriterion("payment_day is null");
            return (Criteria) this;
        }

        public Criteria andPaymentDayIsNotNull() {
            addCriterion("payment_day is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentDayEqualTo(Boolean value) {
            addCriterion("payment_day =", value, "paymentDay");
            return (Criteria) this;
        }

        public Criteria andPaymentDayNotEqualTo(Boolean value) {
            addCriterion("payment_day <>", value, "paymentDay");
            return (Criteria) this;
        }

        public Criteria andPaymentDayGreaterThan(Boolean value) {
            addCriterion("payment_day >", value, "paymentDay");
            return (Criteria) this;
        }

        public Criteria andPaymentDayGreaterThanOrEqualTo(Boolean value) {
            addCriterion("payment_day >=", value, "paymentDay");
            return (Criteria) this;
        }

        public Criteria andPaymentDayLessThan(Boolean value) {
            addCriterion("payment_day <", value, "paymentDay");
            return (Criteria) this;
        }

        public Criteria andPaymentDayLessThanOrEqualTo(Boolean value) {
            addCriterion("payment_day <=", value, "paymentDay");
            return (Criteria) this;
        }

        public Criteria andPaymentDayIn(List<Boolean> values) {
            addCriterion("payment_day in", values, "paymentDay");
            return (Criteria) this;
        }

        public Criteria andPaymentDayNotIn(List<Boolean> values) {
            addCriterion("payment_day not in", values, "paymentDay");
            return (Criteria) this;
        }

        public Criteria andPaymentDayBetween(Boolean value1, Boolean value2) {
            addCriterion("payment_day between", value1, value2, "paymentDay");
            return (Criteria) this;
        }

        public Criteria andPaymentDayNotBetween(Boolean value1, Boolean value2) {
            addCriterion("payment_day not between", value1, value2, "paymentDay");
            return (Criteria) this;
        }

        public Criteria andPaymentAdjustDaysIsNull() {
            addCriterion("payment_adjust_days is null");
            return (Criteria) this;
        }

        public Criteria andPaymentAdjustDaysIsNotNull() {
            addCriterion("payment_adjust_days is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentAdjustDaysEqualTo(Integer value) {
            addCriterion("payment_adjust_days =", value, "paymentAdjustDays");
            return (Criteria) this;
        }

        public Criteria andPaymentAdjustDaysNotEqualTo(Integer value) {
            addCriterion("payment_adjust_days <>", value, "paymentAdjustDays");
            return (Criteria) this;
        }

        public Criteria andPaymentAdjustDaysGreaterThan(Integer value) {
            addCriterion("payment_adjust_days >", value, "paymentAdjustDays");
            return (Criteria) this;
        }

        public Criteria andPaymentAdjustDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("payment_adjust_days >=", value, "paymentAdjustDays");
            return (Criteria) this;
        }

        public Criteria andPaymentAdjustDaysLessThan(Integer value) {
            addCriterion("payment_adjust_days <", value, "paymentAdjustDays");
            return (Criteria) this;
        }

        public Criteria andPaymentAdjustDaysLessThanOrEqualTo(Integer value) {
            addCriterion("payment_adjust_days <=", value, "paymentAdjustDays");
            return (Criteria) this;
        }

        public Criteria andPaymentAdjustDaysIn(List<Integer> values) {
            addCriterion("payment_adjust_days in", values, "paymentAdjustDays");
            return (Criteria) this;
        }

        public Criteria andPaymentAdjustDaysNotIn(List<Integer> values) {
            addCriterion("payment_adjust_days not in", values, "paymentAdjustDays");
            return (Criteria) this;
        }

        public Criteria andPaymentAdjustDaysBetween(Integer value1, Integer value2) {
            addCriterion("payment_adjust_days between", value1, value2, "paymentAdjustDays");
            return (Criteria) this;
        }

        public Criteria andPaymentAdjustDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("payment_adjust_days not between", value1, value2, "paymentAdjustDays");
            return (Criteria) this;
        }

        public Criteria andAccountingManagerIsNull() {
            addCriterion("accounting_manager is null");
            return (Criteria) this;
        }

        public Criteria andAccountingManagerIsNotNull() {
            addCriterion("accounting_manager is not null");
            return (Criteria) this;
        }

        public Criteria andAccountingManagerEqualTo(String value) {
            addCriterion("accounting_manager =", value, "accountingManager");
            return (Criteria) this;
        }

        public Criteria andAccountingManagerNotEqualTo(String value) {
            addCriterion("accounting_manager <>", value, "accountingManager");
            return (Criteria) this;
        }

        public Criteria andAccountingManagerGreaterThan(String value) {
            addCriterion("accounting_manager >", value, "accountingManager");
            return (Criteria) this;
        }

        public Criteria andAccountingManagerGreaterThanOrEqualTo(String value) {
            addCriterion("accounting_manager >=", value, "accountingManager");
            return (Criteria) this;
        }

        public Criteria andAccountingManagerLessThan(String value) {
            addCriterion("accounting_manager <", value, "accountingManager");
            return (Criteria) this;
        }

        public Criteria andAccountingManagerLessThanOrEqualTo(String value) {
            addCriterion("accounting_manager <=", value, "accountingManager");
            return (Criteria) this;
        }

        public Criteria andAccountingManagerLike(String value) {
            addCriterion("accounting_manager like", value, "accountingManager");
            return (Criteria) this;
        }

        public Criteria andAccountingManagerNotLike(String value) {
            addCriterion("accounting_manager not like", value, "accountingManager");
            return (Criteria) this;
        }

        public Criteria andAccountingManagerIn(List<String> values) {
            addCriterion("accounting_manager in", values, "accountingManager");
            return (Criteria) this;
        }

        public Criteria andAccountingManagerNotIn(List<String> values) {
            addCriterion("accounting_manager not in", values, "accountingManager");
            return (Criteria) this;
        }

        public Criteria andAccountingManagerBetween(String value1, String value2) {
            addCriterion("accounting_manager between", value1, value2, "accountingManager");
            return (Criteria) this;
        }

        public Criteria andAccountingManagerNotBetween(String value1, String value2) {
            addCriterion("accounting_manager not between", value1, value2, "accountingManager");
            return (Criteria) this;
        }

        public Criteria andUserRecongIdIsNull() {
            addCriterion("user_recong_id is null");
            return (Criteria) this;
        }

        public Criteria andUserRecongIdIsNotNull() {
            addCriterion("user_recong_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserRecongIdEqualTo(Long value) {
            addCriterion("user_recong_id =", value, "userRecongId");
            return (Criteria) this;
        }

        public Criteria andUserRecongIdNotEqualTo(Long value) {
            addCriterion("user_recong_id <>", value, "userRecongId");
            return (Criteria) this;
        }

        public Criteria andUserRecongIdGreaterThan(Long value) {
            addCriterion("user_recong_id >", value, "userRecongId");
            return (Criteria) this;
        }

        public Criteria andUserRecongIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_recong_id >=", value, "userRecongId");
            return (Criteria) this;
        }

        public Criteria andUserRecongIdLessThan(Long value) {
            addCriterion("user_recong_id <", value, "userRecongId");
            return (Criteria) this;
        }

        public Criteria andUserRecongIdLessThanOrEqualTo(Long value) {
            addCriterion("user_recong_id <=", value, "userRecongId");
            return (Criteria) this;
        }

        public Criteria andUserRecongIdIn(List<Long> values) {
            addCriterion("user_recong_id in", values, "userRecongId");
            return (Criteria) this;
        }

        public Criteria andUserRecongIdNotIn(List<Long> values) {
            addCriterion("user_recong_id not in", values, "userRecongId");
            return (Criteria) this;
        }

        public Criteria andUserRecongIdBetween(Long value1, Long value2) {
            addCriterion("user_recong_id between", value1, value2, "userRecongId");
            return (Criteria) this;
        }

        public Criteria andUserRecongIdNotBetween(Long value1, Long value2) {
            addCriterion("user_recong_id not between", value1, value2, "userRecongId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andTaxAccountantIsNull() {
            addCriterion("tax_accountant is null");
            return (Criteria) this;
        }

        public Criteria andTaxAccountantIsNotNull() {
            addCriterion("tax_accountant is not null");
            return (Criteria) this;
        }

        public Criteria andTaxAccountantEqualTo(String value) {
            addCriterion("tax_accountant =", value, "taxAccountant");
            return (Criteria) this;
        }

        public Criteria andTaxAccountantNotEqualTo(String value) {
            addCriterion("tax_accountant <>", value, "taxAccountant");
            return (Criteria) this;
        }

        public Criteria andTaxAccountantGreaterThan(String value) {
            addCriterion("tax_accountant >", value, "taxAccountant");
            return (Criteria) this;
        }

        public Criteria andTaxAccountantGreaterThanOrEqualTo(String value) {
            addCriterion("tax_accountant >=", value, "taxAccountant");
            return (Criteria) this;
        }

        public Criteria andTaxAccountantLessThan(String value) {
            addCriterion("tax_accountant <", value, "taxAccountant");
            return (Criteria) this;
        }

        public Criteria andTaxAccountantLessThanOrEqualTo(String value) {
            addCriterion("tax_accountant <=", value, "taxAccountant");
            return (Criteria) this;
        }

        public Criteria andTaxAccountantLike(String value) {
            addCriterion("tax_accountant like", value, "taxAccountant");
            return (Criteria) this;
        }

        public Criteria andTaxAccountantNotLike(String value) {
            addCriterion("tax_accountant not like", value, "taxAccountant");
            return (Criteria) this;
        }

        public Criteria andTaxAccountantIn(List<String> values) {
            addCriterion("tax_accountant in", values, "taxAccountant");
            return (Criteria) this;
        }

        public Criteria andTaxAccountantNotIn(List<String> values) {
            addCriterion("tax_accountant not in", values, "taxAccountant");
            return (Criteria) this;
        }

        public Criteria andTaxAccountantBetween(String value1, String value2) {
            addCriterion("tax_accountant between", value1, value2, "taxAccountant");
            return (Criteria) this;
        }

        public Criteria andTaxAccountantNotBetween(String value1, String value2) {
            addCriterion("tax_accountant not between", value1, value2, "taxAccountant");
            return (Criteria) this;
        }

        public Criteria andTaxOfficeIsNull() {
            addCriterion("tax_office is null");
            return (Criteria) this;
        }

        public Criteria andTaxOfficeIsNotNull() {
            addCriterion("tax_office is not null");
            return (Criteria) this;
        }

        public Criteria andTaxOfficeEqualTo(String value) {
            addCriterion("tax_office =", value, "taxOffice");
            return (Criteria) this;
        }

        public Criteria andTaxOfficeNotEqualTo(String value) {
            addCriterion("tax_office <>", value, "taxOffice");
            return (Criteria) this;
        }

        public Criteria andTaxOfficeGreaterThan(String value) {
            addCriterion("tax_office >", value, "taxOffice");
            return (Criteria) this;
        }

        public Criteria andTaxOfficeGreaterThanOrEqualTo(String value) {
            addCriterion("tax_office >=", value, "taxOffice");
            return (Criteria) this;
        }

        public Criteria andTaxOfficeLessThan(String value) {
            addCriterion("tax_office <", value, "taxOffice");
            return (Criteria) this;
        }

        public Criteria andTaxOfficeLessThanOrEqualTo(String value) {
            addCriterion("tax_office <=", value, "taxOffice");
            return (Criteria) this;
        }

        public Criteria andTaxOfficeLike(String value) {
            addCriterion("tax_office like", value, "taxOffice");
            return (Criteria) this;
        }

        public Criteria andTaxOfficeNotLike(String value) {
            addCriterion("tax_office not like", value, "taxOffice");
            return (Criteria) this;
        }

        public Criteria andTaxOfficeIn(List<String> values) {
            addCriterion("tax_office in", values, "taxOffice");
            return (Criteria) this;
        }

        public Criteria andTaxOfficeNotIn(List<String> values) {
            addCriterion("tax_office not in", values, "taxOffice");
            return (Criteria) this;
        }

        public Criteria andTaxOfficeBetween(String value1, String value2) {
            addCriterion("tax_office between", value1, value2, "taxOffice");
            return (Criteria) this;
        }

        public Criteria andTaxOfficeNotBetween(String value1, String value2) {
            addCriterion("tax_office not between", value1, value2, "taxOffice");
            return (Criteria) this;
        }

        public Criteria andDataShareIdIsNull() {
            addCriterion("data_share_id is null");
            return (Criteria) this;
        }

        public Criteria andDataShareIdIsNotNull() {
            addCriterion("data_share_id is not null");
            return (Criteria) this;
        }

        public Criteria andDataShareIdEqualTo(Long value) {
            addCriterion("data_share_id =", value, "dataShareId");
            return (Criteria) this;
        }

        public Criteria andDataShareIdNotEqualTo(Long value) {
            addCriterion("data_share_id <>", value, "dataShareId");
            return (Criteria) this;
        }

        public Criteria andDataShareIdGreaterThan(Long value) {
            addCriterion("data_share_id >", value, "dataShareId");
            return (Criteria) this;
        }

        public Criteria andDataShareIdGreaterThanOrEqualTo(Long value) {
            addCriterion("data_share_id >=", value, "dataShareId");
            return (Criteria) this;
        }

        public Criteria andDataShareIdLessThan(Long value) {
            addCriterion("data_share_id <", value, "dataShareId");
            return (Criteria) this;
        }

        public Criteria andDataShareIdLessThanOrEqualTo(Long value) {
            addCriterion("data_share_id <=", value, "dataShareId");
            return (Criteria) this;
        }

        public Criteria andDataShareIdIn(List<Long> values) {
            addCriterion("data_share_id in", values, "dataShareId");
            return (Criteria) this;
        }

        public Criteria andDataShareIdNotIn(List<Long> values) {
            addCriterion("data_share_id not in", values, "dataShareId");
            return (Criteria) this;
        }

        public Criteria andDataShareIdBetween(Long value1, Long value2) {
            addCriterion("data_share_id between", value1, value2, "dataShareId");
            return (Criteria) this;
        }

        public Criteria andDataShareIdNotBetween(Long value1, Long value2) {
            addCriterion("data_share_id not between", value1, value2, "dataShareId");
            return (Criteria) this;
        }

        public Criteria andMyNumberIsNull() {
            addCriterion("my_number is null");
            return (Criteria) this;
        }

        public Criteria andMyNumberIsNotNull() {
            addCriterion("my_number is not null");
            return (Criteria) this;
        }

        public Criteria andMyNumberEqualTo(Long value) {
            addCriterion("my_number =", value, "myNumber");
            return (Criteria) this;
        }

        public Criteria andMyNumberNotEqualTo(Long value) {
            addCriterion("my_number <>", value, "myNumber");
            return (Criteria) this;
        }

        public Criteria andMyNumberGreaterThan(Long value) {
            addCriterion("my_number >", value, "myNumber");
            return (Criteria) this;
        }

        public Criteria andMyNumberGreaterThanOrEqualTo(Long value) {
            addCriterion("my_number >=", value, "myNumber");
            return (Criteria) this;
        }

        public Criteria andMyNumberLessThan(Long value) {
            addCriterion("my_number <", value, "myNumber");
            return (Criteria) this;
        }

        public Criteria andMyNumberLessThanOrEqualTo(Long value) {
            addCriterion("my_number <=", value, "myNumber");
            return (Criteria) this;
        }

        public Criteria andMyNumberIn(List<Long> values) {
            addCriterion("my_number in", values, "myNumber");
            return (Criteria) this;
        }

        public Criteria andMyNumberNotIn(List<Long> values) {
            addCriterion("my_number not in", values, "myNumber");
            return (Criteria) this;
        }

        public Criteria andMyNumberBetween(Long value1, Long value2) {
            addCriterion("my_number between", value1, value2, "myNumber");
            return (Criteria) this;
        }

        public Criteria andMyNumberNotBetween(Long value1, Long value2) {
            addCriterion("my_number not between", value1, value2, "myNumber");
            return (Criteria) this;
        }

        public Criteria andCompCodeIsNull() {
            addCriterion("comp_code is null");
            return (Criteria) this;
        }

        public Criteria andCompCodeIsNotNull() {
            addCriterion("comp_code is not null");
            return (Criteria) this;
        }

        public Criteria andCompCodeEqualTo(Long value) {
            addCriterion("comp_code =", value, "compCode");
            return (Criteria) this;
        }

        public Criteria andCompCodeNotEqualTo(Long value) {
            addCriterion("comp_code <>", value, "compCode");
            return (Criteria) this;
        }

        public Criteria andCompCodeGreaterThan(Long value) {
            addCriterion("comp_code >", value, "compCode");
            return (Criteria) this;
        }

        public Criteria andCompCodeGreaterThanOrEqualTo(Long value) {
            addCriterion("comp_code >=", value, "compCode");
            return (Criteria) this;
        }

        public Criteria andCompCodeLessThan(Long value) {
            addCriterion("comp_code <", value, "compCode");
            return (Criteria) this;
        }

        public Criteria andCompCodeLessThanOrEqualTo(Long value) {
            addCriterion("comp_code <=", value, "compCode");
            return (Criteria) this;
        }

        public Criteria andCompCodeIn(List<Long> values) {
            addCriterion("comp_code in", values, "compCode");
            return (Criteria) this;
        }

        public Criteria andCompCodeNotIn(List<Long> values) {
            addCriterion("comp_code not in", values, "compCode");
            return (Criteria) this;
        }

        public Criteria andCompCodeBetween(Long value1, Long value2) {
            addCriterion("comp_code between", value1, value2, "compCode");
            return (Criteria) this;
        }

        public Criteria andCompCodeNotBetween(Long value1, Long value2) {
            addCriterion("comp_code not between", value1, value2, "compCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.company
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.company
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}