package jp.co.aliber.accsystem.entity.auto;

public class FixedDeduction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.fixed_deduction.fixed_deduction_id
     *
     * @mbg.generated
     */
    private Long fixedDeductionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.fixed_deduction.travel_fund
     *
     * @mbg.generated
     */
    private Integer travelFund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.fixed_deduction.repayment_borrowings
     *
     * @mbg.generated
     */
    private Integer repaymentBorrowings;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.fixed_deduction.yearend_deduction
     *
     * @mbg.generated
     */
    private Integer yearendDeduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.fixed_deduction.rent_deduction
     *
     * @mbg.generated
     */
    private Integer rentDeduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.fixed_deduction.other_deduction
     *
     * @mbg.generated
     */
    private Integer otherDeduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.fixed_deduction.fixed_deduction_id
     *
     * @return the value of public.fixed_deduction.fixed_deduction_id
     *
     * @mbg.generated
     */
    public Long getFixedDeductionId() {
        return fixedDeductionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.fixed_deduction.fixed_deduction_id
     *
     * @param fixedDeductionId the value for public.fixed_deduction.fixed_deduction_id
     *
     * @mbg.generated
     */
    public void setFixedDeductionId(Long fixedDeductionId) {
        this.fixedDeductionId = fixedDeductionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.fixed_deduction.travel_fund
     *
     * @return the value of public.fixed_deduction.travel_fund
     *
     * @mbg.generated
     */
    public Integer getTravelFund() {
        return travelFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.fixed_deduction.travel_fund
     *
     * @param travelFund the value for public.fixed_deduction.travel_fund
     *
     * @mbg.generated
     */
    public void setTravelFund(Integer travelFund) {
        this.travelFund = travelFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.fixed_deduction.repayment_borrowings
     *
     * @return the value of public.fixed_deduction.repayment_borrowings
     *
     * @mbg.generated
     */
    public Integer getRepaymentBorrowings() {
        return repaymentBorrowings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.fixed_deduction.repayment_borrowings
     *
     * @param repaymentBorrowings the value for public.fixed_deduction.repayment_borrowings
     *
     * @mbg.generated
     */
    public void setRepaymentBorrowings(Integer repaymentBorrowings) {
        this.repaymentBorrowings = repaymentBorrowings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.fixed_deduction.yearend_deduction
     *
     * @return the value of public.fixed_deduction.yearend_deduction
     *
     * @mbg.generated
     */
    public Integer getYearendDeduction() {
        return yearendDeduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.fixed_deduction.yearend_deduction
     *
     * @param yearendDeduction the value for public.fixed_deduction.yearend_deduction
     *
     * @mbg.generated
     */
    public void setYearendDeduction(Integer yearendDeduction) {
        this.yearendDeduction = yearendDeduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.fixed_deduction.rent_deduction
     *
     * @return the value of public.fixed_deduction.rent_deduction
     *
     * @mbg.generated
     */
    public Integer getRentDeduction() {
        return rentDeduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.fixed_deduction.rent_deduction
     *
     * @param rentDeduction the value for public.fixed_deduction.rent_deduction
     *
     * @mbg.generated
     */
    public void setRentDeduction(Integer rentDeduction) {
        this.rentDeduction = rentDeduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.fixed_deduction.other_deduction
     *
     * @return the value of public.fixed_deduction.other_deduction
     *
     * @mbg.generated
     */
    public Integer getOtherDeduction() {
        return otherDeduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.fixed_deduction.other_deduction
     *
     * @param otherDeduction the value for public.fixed_deduction.other_deduction
     *
     * @mbg.generated
     */
    public void setOtherDeduction(Integer otherDeduction) {
        this.otherDeduction = otherDeduction;
    }
}