package jp.co.aliber.accsystem.entity.auto;

public class LList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.l_list.literal_class_id
     *
     * @mbg.generated
     */
    private Integer literalClassId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.l_list.literal_id
     *
     * @mbg.generated
     */
    private Integer literalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.l_list.indicate_letter
     *
     * @mbg.generated
     */
    private String indicateLetter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.l_list.indicate_order
     *
     * @mbg.generated
     */
    private Short indicateOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.l_list.literal_class_id
     *
     * @return the value of public.l_list.literal_class_id
     *
     * @mbg.generated
     */
    public Integer getLiteralClassId() {
        return literalClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.l_list.literal_class_id
     *
     * @param literalClassId the value for public.l_list.literal_class_id
     *
     * @mbg.generated
     */
    public void setLiteralClassId(Integer literalClassId) {
        this.literalClassId = literalClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.l_list.literal_id
     *
     * @return the value of public.l_list.literal_id
     *
     * @mbg.generated
     */
    public Integer getLiteralId() {
        return literalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.l_list.literal_id
     *
     * @param literalId the value for public.l_list.literal_id
     *
     * @mbg.generated
     */
    public void setLiteralId(Integer literalId) {
        this.literalId = literalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.l_list.indicate_letter
     *
     * @return the value of public.l_list.indicate_letter
     *
     * @mbg.generated
     */
    public String getIndicateLetter() {
        return indicateLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.l_list.indicate_letter
     *
     * @param indicateLetter the value for public.l_list.indicate_letter
     *
     * @mbg.generated
     */
    public void setIndicateLetter(String indicateLetter) {
        this.indicateLetter = indicateLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.l_list.indicate_order
     *
     * @return the value of public.l_list.indicate_order
     *
     * @mbg.generated
     */
    public Short getIndicateOrder() {
        return indicateOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.l_list.indicate_order
     *
     * @param indicateOrder the value for public.l_list.indicate_order
     *
     * @mbg.generated
     */
    public void setIndicateOrder(Short indicateOrder) {
        this.indicateOrder = indicateOrder;
    }
}