package jp.co.aliber.accsystem.entity.auto;

public class MStandardReward {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_standard_reward.management_id
     *
     * @mbg.generated
     */
    private Integer managementId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_standard_reward.kbn
     *
     * @mbg.generated
     */
    private Short kbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_standard_reward.level
     *
     * @mbg.generated
     */
    private Short level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.m_standard_reward.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_standard_reward.management_id
     *
     * @return the value of public.m_standard_reward.management_id
     *
     * @mbg.generated
     */
    public Integer getManagementId() {
        return managementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_standard_reward.management_id
     *
     * @param managementId the value for public.m_standard_reward.management_id
     *
     * @mbg.generated
     */
    public void setManagementId(Integer managementId) {
        this.managementId = managementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_standard_reward.kbn
     *
     * @return the value of public.m_standard_reward.kbn
     *
     * @mbg.generated
     */
    public Short getKbn() {
        return kbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_standard_reward.kbn
     *
     * @param kbn the value for public.m_standard_reward.kbn
     *
     * @mbg.generated
     */
    public void setKbn(Short kbn) {
        this.kbn = kbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_standard_reward.level
     *
     * @return the value of public.m_standard_reward.level
     *
     * @mbg.generated
     */
    public Short getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_standard_reward.level
     *
     * @param level the value for public.m_standard_reward.level
     *
     * @mbg.generated
     */
    public void setLevel(Short level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.m_standard_reward.description
     *
     * @return the value of public.m_standard_reward.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.m_standard_reward.description
     *
     * @param description the value for public.m_standard_reward.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }
}