package jp.co.aliber.accsystem.entity.auto;

public class PayDetailsInput {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pay_details_input.pay_details_input_id
     *
     * @mbg.generated
     */
    private Long payDetailsInputId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pay_details_input.basic_pay
     *
     * @mbg.generated
     */
    private Long basicPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pay_details_input.position_pay
     *
     * @mbg.generated
     */
    private Long positionPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pay_details_input.qualification_pay
     *
     * @mbg.generated
     */
    private Long qualificationPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pay_details_input.housing_pay
     *
     * @mbg.generated
     */
    private Long housingPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pay_details_input.family_pay
     *
     * @mbg.generated
     */
    private Long familyPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pay_details_input.others_pay
     *
     * @mbg.generated
     */
    private Long othersPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pay_details_input.transport_fee
     *
     * @mbg.generated
     */
    private Long transportFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pay_details_input.total_pay
     *
     * @mbg.generated
     */
    private Long totalPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pay_details_input.health_insurance
     *
     * @mbg.generated
     */
    private Long healthInsurance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pay_details_input.hand_input1
     *
     * @mbg.generated
     */
    private Boolean handInput1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pay_details_input.welfare_insurance
     *
     * @mbg.generated
     */
    private Long welfareInsurance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pay_details_input.hand_input2
     *
     * @mbg.generated
     */
    private Boolean handInput2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pay_details_input.employ_insurance
     *
     * @mbg.generated
     */
    private Long employInsurance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pay_details_input.hand_input3
     *
     * @mbg.generated
     */
    private Boolean handInput3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pay_details_input.total_insurance
     *
     * @mbg.generated
     */
    private Long totalInsurance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pay_details_input.income_tax
     *
     * @mbg.generated
     */
    private Long incomeTax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pay_details_input.living_tax
     *
     * @mbg.generated
     */
    private Long livingTax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pay_details_input.total_deductible_amount
     *
     * @mbg.generated
     */
    private Long totalDeductibleAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.pay_details_input.subscription_amount
     *
     * @mbg.generated
     */
    private Long subscriptionAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pay_details_input.pay_details_input_id
     *
     * @return the value of public.pay_details_input.pay_details_input_id
     *
     * @mbg.generated
     */
    public Long getPayDetailsInputId() {
        return payDetailsInputId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pay_details_input.pay_details_input_id
     *
     * @param payDetailsInputId the value for public.pay_details_input.pay_details_input_id
     *
     * @mbg.generated
     */
    public void setPayDetailsInputId(Long payDetailsInputId) {
        this.payDetailsInputId = payDetailsInputId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pay_details_input.basic_pay
     *
     * @return the value of public.pay_details_input.basic_pay
     *
     * @mbg.generated
     */
    public Long getBasicPay() {
        return basicPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pay_details_input.basic_pay
     *
     * @param basicPay the value for public.pay_details_input.basic_pay
     *
     * @mbg.generated
     */
    public void setBasicPay(Long basicPay) {
        this.basicPay = basicPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pay_details_input.position_pay
     *
     * @return the value of public.pay_details_input.position_pay
     *
     * @mbg.generated
     */
    public Long getPositionPay() {
        return positionPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pay_details_input.position_pay
     *
     * @param positionPay the value for public.pay_details_input.position_pay
     *
     * @mbg.generated
     */
    public void setPositionPay(Long positionPay) {
        this.positionPay = positionPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pay_details_input.qualification_pay
     *
     * @return the value of public.pay_details_input.qualification_pay
     *
     * @mbg.generated
     */
    public Long getQualificationPay() {
        return qualificationPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pay_details_input.qualification_pay
     *
     * @param qualificationPay the value for public.pay_details_input.qualification_pay
     *
     * @mbg.generated
     */
    public void setQualificationPay(Long qualificationPay) {
        this.qualificationPay = qualificationPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pay_details_input.housing_pay
     *
     * @return the value of public.pay_details_input.housing_pay
     *
     * @mbg.generated
     */
    public Long getHousingPay() {
        return housingPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pay_details_input.housing_pay
     *
     * @param housingPay the value for public.pay_details_input.housing_pay
     *
     * @mbg.generated
     */
    public void setHousingPay(Long housingPay) {
        this.housingPay = housingPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pay_details_input.family_pay
     *
     * @return the value of public.pay_details_input.family_pay
     *
     * @mbg.generated
     */
    public Long getFamilyPay() {
        return familyPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pay_details_input.family_pay
     *
     * @param familyPay the value for public.pay_details_input.family_pay
     *
     * @mbg.generated
     */
    public void setFamilyPay(Long familyPay) {
        this.familyPay = familyPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pay_details_input.others_pay
     *
     * @return the value of public.pay_details_input.others_pay
     *
     * @mbg.generated
     */
    public Long getOthersPay() {
        return othersPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pay_details_input.others_pay
     *
     * @param othersPay the value for public.pay_details_input.others_pay
     *
     * @mbg.generated
     */
    public void setOthersPay(Long othersPay) {
        this.othersPay = othersPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pay_details_input.transport_fee
     *
     * @return the value of public.pay_details_input.transport_fee
     *
     * @mbg.generated
     */
    public Long getTransportFee() {
        return transportFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pay_details_input.transport_fee
     *
     * @param transportFee the value for public.pay_details_input.transport_fee
     *
     * @mbg.generated
     */
    public void setTransportFee(Long transportFee) {
        this.transportFee = transportFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pay_details_input.total_pay
     *
     * @return the value of public.pay_details_input.total_pay
     *
     * @mbg.generated
     */
    public Long getTotalPay() {
        return totalPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pay_details_input.total_pay
     *
     * @param totalPay the value for public.pay_details_input.total_pay
     *
     * @mbg.generated
     */
    public void setTotalPay(Long totalPay) {
        this.totalPay = totalPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pay_details_input.health_insurance
     *
     * @return the value of public.pay_details_input.health_insurance
     *
     * @mbg.generated
     */
    public Long getHealthInsurance() {
        return healthInsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pay_details_input.health_insurance
     *
     * @param healthInsurance the value for public.pay_details_input.health_insurance
     *
     * @mbg.generated
     */
    public void setHealthInsurance(Long healthInsurance) {
        this.healthInsurance = healthInsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pay_details_input.hand_input1
     *
     * @return the value of public.pay_details_input.hand_input1
     *
     * @mbg.generated
     */
    public Boolean getHandInput1() {
        return handInput1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pay_details_input.hand_input1
     *
     * @param handInput1 the value for public.pay_details_input.hand_input1
     *
     * @mbg.generated
     */
    public void setHandInput1(Boolean handInput1) {
        this.handInput1 = handInput1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pay_details_input.welfare_insurance
     *
     * @return the value of public.pay_details_input.welfare_insurance
     *
     * @mbg.generated
     */
    public Long getWelfareInsurance() {
        return welfareInsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pay_details_input.welfare_insurance
     *
     * @param welfareInsurance the value for public.pay_details_input.welfare_insurance
     *
     * @mbg.generated
     */
    public void setWelfareInsurance(Long welfareInsurance) {
        this.welfareInsurance = welfareInsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pay_details_input.hand_input2
     *
     * @return the value of public.pay_details_input.hand_input2
     *
     * @mbg.generated
     */
    public Boolean getHandInput2() {
        return handInput2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pay_details_input.hand_input2
     *
     * @param handInput2 the value for public.pay_details_input.hand_input2
     *
     * @mbg.generated
     */
    public void setHandInput2(Boolean handInput2) {
        this.handInput2 = handInput2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pay_details_input.employ_insurance
     *
     * @return the value of public.pay_details_input.employ_insurance
     *
     * @mbg.generated
     */
    public Long getEmployInsurance() {
        return employInsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pay_details_input.employ_insurance
     *
     * @param employInsurance the value for public.pay_details_input.employ_insurance
     *
     * @mbg.generated
     */
    public void setEmployInsurance(Long employInsurance) {
        this.employInsurance = employInsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pay_details_input.hand_input3
     *
     * @return the value of public.pay_details_input.hand_input3
     *
     * @mbg.generated
     */
    public Boolean getHandInput3() {
        return handInput3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pay_details_input.hand_input3
     *
     * @param handInput3 the value for public.pay_details_input.hand_input3
     *
     * @mbg.generated
     */
    public void setHandInput3(Boolean handInput3) {
        this.handInput3 = handInput3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pay_details_input.total_insurance
     *
     * @return the value of public.pay_details_input.total_insurance
     *
     * @mbg.generated
     */
    public Long getTotalInsurance() {
        return totalInsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pay_details_input.total_insurance
     *
     * @param totalInsurance the value for public.pay_details_input.total_insurance
     *
     * @mbg.generated
     */
    public void setTotalInsurance(Long totalInsurance) {
        this.totalInsurance = totalInsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pay_details_input.income_tax
     *
     * @return the value of public.pay_details_input.income_tax
     *
     * @mbg.generated
     */
    public Long getIncomeTax() {
        return incomeTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pay_details_input.income_tax
     *
     * @param incomeTax the value for public.pay_details_input.income_tax
     *
     * @mbg.generated
     */
    public void setIncomeTax(Long incomeTax) {
        this.incomeTax = incomeTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pay_details_input.living_tax
     *
     * @return the value of public.pay_details_input.living_tax
     *
     * @mbg.generated
     */
    public Long getLivingTax() {
        return livingTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pay_details_input.living_tax
     *
     * @param livingTax the value for public.pay_details_input.living_tax
     *
     * @mbg.generated
     */
    public void setLivingTax(Long livingTax) {
        this.livingTax = livingTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pay_details_input.total_deductible_amount
     *
     * @return the value of public.pay_details_input.total_deductible_amount
     *
     * @mbg.generated
     */
    public Long getTotalDeductibleAmount() {
        return totalDeductibleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pay_details_input.total_deductible_amount
     *
     * @param totalDeductibleAmount the value for public.pay_details_input.total_deductible_amount
     *
     * @mbg.generated
     */
    public void setTotalDeductibleAmount(Long totalDeductibleAmount) {
        this.totalDeductibleAmount = totalDeductibleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.pay_details_input.subscription_amount
     *
     * @return the value of public.pay_details_input.subscription_amount
     *
     * @mbg.generated
     */
    public Long getSubscriptionAmount() {
        return subscriptionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.pay_details_input.subscription_amount
     *
     * @param subscriptionAmount the value for public.pay_details_input.subscription_amount
     *
     * @mbg.generated
     */
    public void setSubscriptionAmount(Long subscriptionAmount) {
        this.subscriptionAmount = subscriptionAmount;
    }
}