package jp.co.aliber.accsystem.entity.auto;

import java.util.Date;

public class TEmployeeFixedPayment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_fixed_payment.employee_id
     *
     * @mbg.generated
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_fixed_payment.comp_id
     *
     * @mbg.generated
     */
    private Integer compId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_fixed_payment.basic_salary
     *
     * @mbg.generated
     */
    private Integer basicSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_fixed_payment.position_allowance
     *
     * @mbg.generated
     */
    private Integer positionAllowance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_fixed_payment.qualification_allowance
     *
     * @mbg.generated
     */
    private Integer qualificationAllowance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_fixed_payment.house_allowance
     *
     * @mbg.generated
     */
    private Integer houseAllowance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_fixed_payment.family_allowance
     *
     * @mbg.generated
     */
    private Integer familyAllowance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_fixed_payment.other_allowance
     *
     * @mbg.generated
     */
    private Integer otherAllowance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_fixed_payment.transport_fee
     *
     * @mbg.generated
     */
    private Integer transportFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_fixed_payment.delete_flg
     *
     * @mbg.generated
     */
    private Boolean deleteFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_fixed_payment.regist_date
     *
     * @mbg.generated
     */
    private Date registDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_fixed_payment.regist_id
     *
     * @mbg.generated
     */
    private Integer registId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_fixed_payment.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_fixed_payment.update_id
     *
     * @mbg.generated
     */
    private Integer updateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_fixed_payment.employee_id
     *
     * @return the value of public.t_employee_fixed_payment.employee_id
     *
     * @mbg.generated
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_fixed_payment.employee_id
     *
     * @param employeeId the value for public.t_employee_fixed_payment.employee_id
     *
     * @mbg.generated
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_fixed_payment.comp_id
     *
     * @return the value of public.t_employee_fixed_payment.comp_id
     *
     * @mbg.generated
     */
    public Integer getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_fixed_payment.comp_id
     *
     * @param compId the value for public.t_employee_fixed_payment.comp_id
     *
     * @mbg.generated
     */
    public void setCompId(Integer compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_fixed_payment.basic_salary
     *
     * @return the value of public.t_employee_fixed_payment.basic_salary
     *
     * @mbg.generated
     */
    public Integer getBasicSalary() {
        return basicSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_fixed_payment.basic_salary
     *
     * @param basicSalary the value for public.t_employee_fixed_payment.basic_salary
     *
     * @mbg.generated
     */
    public void setBasicSalary(Integer basicSalary) {
        this.basicSalary = basicSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_fixed_payment.position_allowance
     *
     * @return the value of public.t_employee_fixed_payment.position_allowance
     *
     * @mbg.generated
     */
    public Integer getPositionAllowance() {
        return positionAllowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_fixed_payment.position_allowance
     *
     * @param positionAllowance the value for public.t_employee_fixed_payment.position_allowance
     *
     * @mbg.generated
     */
    public void setPositionAllowance(Integer positionAllowance) {
        this.positionAllowance = positionAllowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_fixed_payment.qualification_allowance
     *
     * @return the value of public.t_employee_fixed_payment.qualification_allowance
     *
     * @mbg.generated
     */
    public Integer getQualificationAllowance() {
        return qualificationAllowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_fixed_payment.qualification_allowance
     *
     * @param qualificationAllowance the value for public.t_employee_fixed_payment.qualification_allowance
     *
     * @mbg.generated
     */
    public void setQualificationAllowance(Integer qualificationAllowance) {
        this.qualificationAllowance = qualificationAllowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_fixed_payment.house_allowance
     *
     * @return the value of public.t_employee_fixed_payment.house_allowance
     *
     * @mbg.generated
     */
    public Integer getHouseAllowance() {
        return houseAllowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_fixed_payment.house_allowance
     *
     * @param houseAllowance the value for public.t_employee_fixed_payment.house_allowance
     *
     * @mbg.generated
     */
    public void setHouseAllowance(Integer houseAllowance) {
        this.houseAllowance = houseAllowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_fixed_payment.family_allowance
     *
     * @return the value of public.t_employee_fixed_payment.family_allowance
     *
     * @mbg.generated
     */
    public Integer getFamilyAllowance() {
        return familyAllowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_fixed_payment.family_allowance
     *
     * @param familyAllowance the value for public.t_employee_fixed_payment.family_allowance
     *
     * @mbg.generated
     */
    public void setFamilyAllowance(Integer familyAllowance) {
        this.familyAllowance = familyAllowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_fixed_payment.other_allowance
     *
     * @return the value of public.t_employee_fixed_payment.other_allowance
     *
     * @mbg.generated
     */
    public Integer getOtherAllowance() {
        return otherAllowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_fixed_payment.other_allowance
     *
     * @param otherAllowance the value for public.t_employee_fixed_payment.other_allowance
     *
     * @mbg.generated
     */
    public void setOtherAllowance(Integer otherAllowance) {
        this.otherAllowance = otherAllowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_fixed_payment.transport_fee
     *
     * @return the value of public.t_employee_fixed_payment.transport_fee
     *
     * @mbg.generated
     */
    public Integer getTransportFee() {
        return transportFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_fixed_payment.transport_fee
     *
     * @param transportFee the value for public.t_employee_fixed_payment.transport_fee
     *
     * @mbg.generated
     */
    public void setTransportFee(Integer transportFee) {
        this.transportFee = transportFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_fixed_payment.delete_flg
     *
     * @return the value of public.t_employee_fixed_payment.delete_flg
     *
     * @mbg.generated
     */
    public Boolean getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_fixed_payment.delete_flg
     *
     * @param deleteFlg the value for public.t_employee_fixed_payment.delete_flg
     *
     * @mbg.generated
     */
    public void setDeleteFlg(Boolean deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_fixed_payment.regist_date
     *
     * @return the value of public.t_employee_fixed_payment.regist_date
     *
     * @mbg.generated
     */
    public Date getRegistDate() {
        return registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_fixed_payment.regist_date
     *
     * @param registDate the value for public.t_employee_fixed_payment.regist_date
     *
     * @mbg.generated
     */
    public void setRegistDate(Date registDate) {
        this.registDate = registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_fixed_payment.regist_id
     *
     * @return the value of public.t_employee_fixed_payment.regist_id
     *
     * @mbg.generated
     */
    public Integer getRegistId() {
        return registId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_fixed_payment.regist_id
     *
     * @param registId the value for public.t_employee_fixed_payment.regist_id
     *
     * @mbg.generated
     */
    public void setRegistId(Integer registId) {
        this.registId = registId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_fixed_payment.update_date
     *
     * @return the value of public.t_employee_fixed_payment.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_fixed_payment.update_date
     *
     * @param updateDate the value for public.t_employee_fixed_payment.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_fixed_payment.update_id
     *
     * @return the value of public.t_employee_fixed_payment.update_id
     *
     * @mbg.generated
     */
    public Integer getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_fixed_payment.update_id
     *
     * @param updateId the value for public.t_employee_fixed_payment.update_id
     *
     * @mbg.generated
     */
    public void setUpdateId(Integer updateId) {
        this.updateId = updateId;
    }
}