package jp.co.aliber.accsystem.entity.auto;

import java.util.Date;

public class TEmployee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee.employee_id
     *
     * @mbg.generated
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee.comp_id
     *
     * @mbg.generated
     */
    private Integer compId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee.employee_no
     *
     * @mbg.generated
     */
    private Integer employeeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee.last_name
     *
     * @mbg.generated
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee.first_name
     *
     * @mbg.generated
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee.last_name_kana
     *
     * @mbg.generated
     */
    private String lastNameKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee.first_name_kana
     *
     * @mbg.generated
     */
    private String firstNameKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee.sex
     *
     * @mbg.generated
     */
    private Boolean sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee.dept_id
     *
     * @mbg.generated
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee.mail_address
     *
     * @mbg.generated
     */
    private String mailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee.delete_flg
     *
     * @mbg.generated
     */
    private Boolean deleteFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee.regist_date
     *
     * @mbg.generated
     */
    private Date registDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee.regist_id
     *
     * @mbg.generated
     */
    private Integer registId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee.update_id
     *
     * @mbg.generated
     */
    private Integer updateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee.employee_id
     *
     * @return the value of public.t_employee.employee_id
     *
     * @mbg.generated
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee.employee_id
     *
     * @param employeeId the value for public.t_employee.employee_id
     *
     * @mbg.generated
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee.comp_id
     *
     * @return the value of public.t_employee.comp_id
     *
     * @mbg.generated
     */
    public Integer getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee.comp_id
     *
     * @param compId the value for public.t_employee.comp_id
     *
     * @mbg.generated
     */
    public void setCompId(Integer compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee.employee_no
     *
     * @return the value of public.t_employee.employee_no
     *
     * @mbg.generated
     */
    public Integer getEmployeeNo() {
        return employeeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee.employee_no
     *
     * @param employeeNo the value for public.t_employee.employee_no
     *
     * @mbg.generated
     */
    public void setEmployeeNo(Integer employeeNo) {
        this.employeeNo = employeeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee.last_name
     *
     * @return the value of public.t_employee.last_name
     *
     * @mbg.generated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee.last_name
     *
     * @param lastName the value for public.t_employee.last_name
     *
     * @mbg.generated
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee.first_name
     *
     * @return the value of public.t_employee.first_name
     *
     * @mbg.generated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee.first_name
     *
     * @param firstName the value for public.t_employee.first_name
     *
     * @mbg.generated
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee.last_name_kana
     *
     * @return the value of public.t_employee.last_name_kana
     *
     * @mbg.generated
     */
    public String getLastNameKana() {
        return lastNameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee.last_name_kana
     *
     * @param lastNameKana the value for public.t_employee.last_name_kana
     *
     * @mbg.generated
     */
    public void setLastNameKana(String lastNameKana) {
        this.lastNameKana = lastNameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee.first_name_kana
     *
     * @return the value of public.t_employee.first_name_kana
     *
     * @mbg.generated
     */
    public String getFirstNameKana() {
        return firstNameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee.first_name_kana
     *
     * @param firstNameKana the value for public.t_employee.first_name_kana
     *
     * @mbg.generated
     */
    public void setFirstNameKana(String firstNameKana) {
        this.firstNameKana = firstNameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee.sex
     *
     * @return the value of public.t_employee.sex
     *
     * @mbg.generated
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee.sex
     *
     * @param sex the value for public.t_employee.sex
     *
     * @mbg.generated
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee.dept_id
     *
     * @return the value of public.t_employee.dept_id
     *
     * @mbg.generated
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee.dept_id
     *
     * @param deptId the value for public.t_employee.dept_id
     *
     * @mbg.generated
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee.mail_address
     *
     * @return the value of public.t_employee.mail_address
     *
     * @mbg.generated
     */
    public String getMailAddress() {
        return mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee.mail_address
     *
     * @param mailAddress the value for public.t_employee.mail_address
     *
     * @mbg.generated
     */
    public void setMailAddress(String mailAddress) {
        this.mailAddress = mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee.delete_flg
     *
     * @return the value of public.t_employee.delete_flg
     *
     * @mbg.generated
     */
    public Boolean getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee.delete_flg
     *
     * @param deleteFlg the value for public.t_employee.delete_flg
     *
     * @mbg.generated
     */
    public void setDeleteFlg(Boolean deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee.regist_date
     *
     * @return the value of public.t_employee.regist_date
     *
     * @mbg.generated
     */
    public Date getRegistDate() {
        return registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee.regist_date
     *
     * @param registDate the value for public.t_employee.regist_date
     *
     * @mbg.generated
     */
    public void setRegistDate(Date registDate) {
        this.registDate = registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee.regist_id
     *
     * @return the value of public.t_employee.regist_id
     *
     * @mbg.generated
     */
    public Integer getRegistId() {
        return registId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee.regist_id
     *
     * @param registId the value for public.t_employee.regist_id
     *
     * @mbg.generated
     */
    public void setRegistId(Integer registId) {
        this.registId = registId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee.update_date
     *
     * @return the value of public.t_employee.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee.update_date
     *
     * @param updateDate the value for public.t_employee.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee.update_id
     *
     * @return the value of public.t_employee.update_id
     *
     * @mbg.generated
     */
    public Integer getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee.update_id
     *
     * @param updateId the value for public.t_employee.update_id
     *
     * @mbg.generated
     */
    public void setUpdateId(Integer updateId) {
        this.updateId = updateId;
    }
}