package jp.co.aliber.accsystem.entity.auto;

import java.util.Date;

public class TEmployeeSocialInsurance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_social_insurance.employee_id
     *
     * @mbg.generated
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_social_insurance.comp_id
     *
     * @mbg.generated
     */
    private Integer compId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_social_insurance.employ_insur_join_flg
     *
     * @mbg.generated
     */
    private Short employInsurJoinFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_social_insurance.health_insur_join_flg
     *
     * @mbg.generated
     */
    private Short healthInsurJoinFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_social_insurance.health_insur_join_catagory
     *
     * @mbg.generated
     */
    private Short healthInsurJoinCatagory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_social_insurance.health_insur_standard_reward_level
     *
     * @mbg.generated
     */
    private Integer healthInsurStandardRewardLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_social_insurance.insurers_no
     *
     * @mbg.generated
     */
    private String insurersNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_social_insurance.insured_sort_no
     *
     * @mbg.generated
     */
    private String insuredSortNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_social_insurance.welfare_join_flg
     *
     * @mbg.generated
     */
    private Boolean welfareJoinFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_social_insurance.welfare_standard_reward_level
     *
     * @mbg.generated
     */
    private Integer welfareStandardRewardLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_social_insurance.basic_welfare_no
     *
     * @mbg.generated
     */
    private String basicWelfareNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_social_insurance.welfare_fund_join_flg
     *
     * @mbg.generated
     */
    private Boolean welfareFundJoinFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_social_insurance.delete_flg
     *
     * @mbg.generated
     */
    private Boolean deleteFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_social_insurance.regist_date
     *
     * @mbg.generated
     */
    private Date registDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_social_insurance.regist_id
     *
     * @mbg.generated
     */
    private Integer registId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_social_insurance.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_employee_social_insurance.update_id
     *
     * @mbg.generated
     */
    private Integer updateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_social_insurance.employee_id
     *
     * @return the value of public.t_employee_social_insurance.employee_id
     *
     * @mbg.generated
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_social_insurance.employee_id
     *
     * @param employeeId the value for public.t_employee_social_insurance.employee_id
     *
     * @mbg.generated
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_social_insurance.comp_id
     *
     * @return the value of public.t_employee_social_insurance.comp_id
     *
     * @mbg.generated
     */
    public Integer getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_social_insurance.comp_id
     *
     * @param compId the value for public.t_employee_social_insurance.comp_id
     *
     * @mbg.generated
     */
    public void setCompId(Integer compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_social_insurance.employ_insur_join_flg
     *
     * @return the value of public.t_employee_social_insurance.employ_insur_join_flg
     *
     * @mbg.generated
     */
    public Short getEmployInsurJoinFlg() {
        return employInsurJoinFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_social_insurance.employ_insur_join_flg
     *
     * @param employInsurJoinFlg the value for public.t_employee_social_insurance.employ_insur_join_flg
     *
     * @mbg.generated
     */
    public void setEmployInsurJoinFlg(Short employInsurJoinFlg) {
        this.employInsurJoinFlg = employInsurJoinFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_social_insurance.health_insur_join_flg
     *
     * @return the value of public.t_employee_social_insurance.health_insur_join_flg
     *
     * @mbg.generated
     */
    public Short getHealthInsurJoinFlg() {
        return healthInsurJoinFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_social_insurance.health_insur_join_flg
     *
     * @param healthInsurJoinFlg the value for public.t_employee_social_insurance.health_insur_join_flg
     *
     * @mbg.generated
     */
    public void setHealthInsurJoinFlg(Short healthInsurJoinFlg) {
        this.healthInsurJoinFlg = healthInsurJoinFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_social_insurance.health_insur_join_catagory
     *
     * @return the value of public.t_employee_social_insurance.health_insur_join_catagory
     *
     * @mbg.generated
     */
    public Short getHealthInsurJoinCatagory() {
        return healthInsurJoinCatagory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_social_insurance.health_insur_join_catagory
     *
     * @param healthInsurJoinCatagory the value for public.t_employee_social_insurance.health_insur_join_catagory
     *
     * @mbg.generated
     */
    public void setHealthInsurJoinCatagory(Short healthInsurJoinCatagory) {
        this.healthInsurJoinCatagory = healthInsurJoinCatagory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_social_insurance.health_insur_standard_reward_level
     *
     * @return the value of public.t_employee_social_insurance.health_insur_standard_reward_level
     *
     * @mbg.generated
     */
    public Integer getHealthInsurStandardRewardLevel() {
        return healthInsurStandardRewardLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_social_insurance.health_insur_standard_reward_level
     *
     * @param healthInsurStandardRewardLevel the value for public.t_employee_social_insurance.health_insur_standard_reward_level
     *
     * @mbg.generated
     */
    public void setHealthInsurStandardRewardLevel(Integer healthInsurStandardRewardLevel) {
        this.healthInsurStandardRewardLevel = healthInsurStandardRewardLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_social_insurance.insurers_no
     *
     * @return the value of public.t_employee_social_insurance.insurers_no
     *
     * @mbg.generated
     */
    public String getInsurersNo() {
        return insurersNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_social_insurance.insurers_no
     *
     * @param insurersNo the value for public.t_employee_social_insurance.insurers_no
     *
     * @mbg.generated
     */
    public void setInsurersNo(String insurersNo) {
        this.insurersNo = insurersNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_social_insurance.insured_sort_no
     *
     * @return the value of public.t_employee_social_insurance.insured_sort_no
     *
     * @mbg.generated
     */
    public String getInsuredSortNo() {
        return insuredSortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_social_insurance.insured_sort_no
     *
     * @param insuredSortNo the value for public.t_employee_social_insurance.insured_sort_no
     *
     * @mbg.generated
     */
    public void setInsuredSortNo(String insuredSortNo) {
        this.insuredSortNo = insuredSortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_social_insurance.welfare_join_flg
     *
     * @return the value of public.t_employee_social_insurance.welfare_join_flg
     *
     * @mbg.generated
     */
    public Boolean getWelfareJoinFlg() {
        return welfareJoinFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_social_insurance.welfare_join_flg
     *
     * @param welfareJoinFlg the value for public.t_employee_social_insurance.welfare_join_flg
     *
     * @mbg.generated
     */
    public void setWelfareJoinFlg(Boolean welfareJoinFlg) {
        this.welfareJoinFlg = welfareJoinFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_social_insurance.welfare_standard_reward_level
     *
     * @return the value of public.t_employee_social_insurance.welfare_standard_reward_level
     *
     * @mbg.generated
     */
    public Integer getWelfareStandardRewardLevel() {
        return welfareStandardRewardLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_social_insurance.welfare_standard_reward_level
     *
     * @param welfareStandardRewardLevel the value for public.t_employee_social_insurance.welfare_standard_reward_level
     *
     * @mbg.generated
     */
    public void setWelfareStandardRewardLevel(Integer welfareStandardRewardLevel) {
        this.welfareStandardRewardLevel = welfareStandardRewardLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_social_insurance.basic_welfare_no
     *
     * @return the value of public.t_employee_social_insurance.basic_welfare_no
     *
     * @mbg.generated
     */
    public String getBasicWelfareNo() {
        return basicWelfareNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_social_insurance.basic_welfare_no
     *
     * @param basicWelfareNo the value for public.t_employee_social_insurance.basic_welfare_no
     *
     * @mbg.generated
     */
    public void setBasicWelfareNo(String basicWelfareNo) {
        this.basicWelfareNo = basicWelfareNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_social_insurance.welfare_fund_join_flg
     *
     * @return the value of public.t_employee_social_insurance.welfare_fund_join_flg
     *
     * @mbg.generated
     */
    public Boolean getWelfareFundJoinFlg() {
        return welfareFundJoinFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_social_insurance.welfare_fund_join_flg
     *
     * @param welfareFundJoinFlg the value for public.t_employee_social_insurance.welfare_fund_join_flg
     *
     * @mbg.generated
     */
    public void setWelfareFundJoinFlg(Boolean welfareFundJoinFlg) {
        this.welfareFundJoinFlg = welfareFundJoinFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_social_insurance.delete_flg
     *
     * @return the value of public.t_employee_social_insurance.delete_flg
     *
     * @mbg.generated
     */
    public Boolean getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_social_insurance.delete_flg
     *
     * @param deleteFlg the value for public.t_employee_social_insurance.delete_flg
     *
     * @mbg.generated
     */
    public void setDeleteFlg(Boolean deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_social_insurance.regist_date
     *
     * @return the value of public.t_employee_social_insurance.regist_date
     *
     * @mbg.generated
     */
    public Date getRegistDate() {
        return registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_social_insurance.regist_date
     *
     * @param registDate the value for public.t_employee_social_insurance.regist_date
     *
     * @mbg.generated
     */
    public void setRegistDate(Date registDate) {
        this.registDate = registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_social_insurance.regist_id
     *
     * @return the value of public.t_employee_social_insurance.regist_id
     *
     * @mbg.generated
     */
    public Integer getRegistId() {
        return registId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_social_insurance.regist_id
     *
     * @param registId the value for public.t_employee_social_insurance.regist_id
     *
     * @mbg.generated
     */
    public void setRegistId(Integer registId) {
        this.registId = registId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_social_insurance.update_date
     *
     * @return the value of public.t_employee_social_insurance.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_social_insurance.update_date
     *
     * @param updateDate the value for public.t_employee_social_insurance.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_employee_social_insurance.update_id
     *
     * @return the value of public.t_employee_social_insurance.update_id
     *
     * @mbg.generated
     */
    public Integer getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_employee_social_insurance.update_id
     *
     * @param updateId the value for public.t_employee_social_insurance.update_id
     *
     * @mbg.generated
     */
    public void setUpdateId(Integer updateId) {
        this.updateId = updateId;
    }
}