package jp.co.aliber.accsystem.entity.auto;

public class Test {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.test.testid
     *
     * @mbggenerated
     */
    private Long testid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.test.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.test.testid
     *
     * @return the value of public.test.testid
     *
     * @mbggenerated
     */
    public Long getTestid() {
        return testid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.test.testid
     *
     * @param testid the value for public.test.testid
     *
     * @mbggenerated
     */
    public void setTestid(Long testid) {
        this.testid = testid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.test.name
     *
     * @return the value of public.test.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.test.name
     *
     * @param name the value for public.test.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }
}