package jp.co.aliber.accsystem.entity.auto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TInsuranceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.t_insurance
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.t_insurance
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.t_insurance
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_insurance
     *
     * @mbg.generated
     */
    public TInsuranceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_insurance
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_insurance
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_insurance
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_insurance
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_insurance
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_insurance
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_insurance
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_insurance
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_insurance
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_insurance
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.t_insurance
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCompIdIsNull() {
            addCriterion("comp_id is null");
            return (Criteria) this;
        }

        public Criteria andCompIdIsNotNull() {
            addCriterion("comp_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompIdEqualTo(Integer value) {
            addCriterion("comp_id =", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdNotEqualTo(Integer value) {
            addCriterion("comp_id <>", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdGreaterThan(Integer value) {
            addCriterion("comp_id >", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("comp_id >=", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdLessThan(Integer value) {
            addCriterion("comp_id <", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdLessThanOrEqualTo(Integer value) {
            addCriterion("comp_id <=", value, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdIn(List<Integer> values) {
            addCriterion("comp_id in", values, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdNotIn(List<Integer> values) {
            addCriterion("comp_id not in", values, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdBetween(Integer value1, Integer value2) {
            addCriterion("comp_id between", value1, value2, "compId");
            return (Criteria) this;
        }

        public Criteria andCompIdNotBetween(Integer value1, Integer value2) {
            addCriterion("comp_id not between", value1, value2, "compId");
            return (Criteria) this;
        }

        public Criteria andEmployInsurRateIsNull() {
            addCriterion("employ_insur_rate is null");
            return (Criteria) this;
        }

        public Criteria andEmployInsurRateIsNotNull() {
            addCriterion("employ_insur_rate is not null");
            return (Criteria) this;
        }

        public Criteria andEmployInsurRateEqualTo(BigDecimal value) {
            addCriterion("employ_insur_rate =", value, "employInsurRate");
            return (Criteria) this;
        }

        public Criteria andEmployInsurRateNotEqualTo(BigDecimal value) {
            addCriterion("employ_insur_rate <>", value, "employInsurRate");
            return (Criteria) this;
        }

        public Criteria andEmployInsurRateGreaterThan(BigDecimal value) {
            addCriterion("employ_insur_rate >", value, "employInsurRate");
            return (Criteria) this;
        }

        public Criteria andEmployInsurRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("employ_insur_rate >=", value, "employInsurRate");
            return (Criteria) this;
        }

        public Criteria andEmployInsurRateLessThan(BigDecimal value) {
            addCriterion("employ_insur_rate <", value, "employInsurRate");
            return (Criteria) this;
        }

        public Criteria andEmployInsurRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("employ_insur_rate <=", value, "employInsurRate");
            return (Criteria) this;
        }

        public Criteria andEmployInsurRateIn(List<BigDecimal> values) {
            addCriterion("employ_insur_rate in", values, "employInsurRate");
            return (Criteria) this;
        }

        public Criteria andEmployInsurRateNotIn(List<BigDecimal> values) {
            addCriterion("employ_insur_rate not in", values, "employInsurRate");
            return (Criteria) this;
        }

        public Criteria andEmployInsurRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("employ_insur_rate between", value1, value2, "employInsurRate");
            return (Criteria) this;
        }

        public Criteria andEmployInsurRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("employ_insur_rate not between", value1, value2, "employInsurRate");
            return (Criteria) this;
        }

        public Criteria andEmployRoundingIsNull() {
            addCriterion("employ_rounding is null");
            return (Criteria) this;
        }

        public Criteria andEmployRoundingIsNotNull() {
            addCriterion("employ_rounding is not null");
            return (Criteria) this;
        }

        public Criteria andEmployRoundingEqualTo(Integer value) {
            addCriterion("employ_rounding =", value, "employRounding");
            return (Criteria) this;
        }

        public Criteria andEmployRoundingNotEqualTo(Integer value) {
            addCriterion("employ_rounding <>", value, "employRounding");
            return (Criteria) this;
        }

        public Criteria andEmployRoundingGreaterThan(Integer value) {
            addCriterion("employ_rounding >", value, "employRounding");
            return (Criteria) this;
        }

        public Criteria andEmployRoundingGreaterThanOrEqualTo(Integer value) {
            addCriterion("employ_rounding >=", value, "employRounding");
            return (Criteria) this;
        }

        public Criteria andEmployRoundingLessThan(Integer value) {
            addCriterion("employ_rounding <", value, "employRounding");
            return (Criteria) this;
        }

        public Criteria andEmployRoundingLessThanOrEqualTo(Integer value) {
            addCriterion("employ_rounding <=", value, "employRounding");
            return (Criteria) this;
        }

        public Criteria andEmployRoundingIn(List<Integer> values) {
            addCriterion("employ_rounding in", values, "employRounding");
            return (Criteria) this;
        }

        public Criteria andEmployRoundingNotIn(List<Integer> values) {
            addCriterion("employ_rounding not in", values, "employRounding");
            return (Criteria) this;
        }

        public Criteria andEmployRoundingBetween(Integer value1, Integer value2) {
            addCriterion("employ_rounding between", value1, value2, "employRounding");
            return (Criteria) this;
        }

        public Criteria andEmployRoundingNotBetween(Integer value1, Integer value2) {
            addCriterion("employ_rounding not between", value1, value2, "employRounding");
            return (Criteria) this;
        }

        public Criteria andHealthInsurRateNoNursingIsNull() {
            addCriterion("health_insur_rate_no_nursing is null");
            return (Criteria) this;
        }

        public Criteria andHealthInsurRateNoNursingIsNotNull() {
            addCriterion("health_insur_rate_no_nursing is not null");
            return (Criteria) this;
        }

        public Criteria andHealthInsurRateNoNursingEqualTo(BigDecimal value) {
            addCriterion("health_insur_rate_no_nursing =", value, "healthInsurRateNoNursing");
            return (Criteria) this;
        }

        public Criteria andHealthInsurRateNoNursingNotEqualTo(BigDecimal value) {
            addCriterion("health_insur_rate_no_nursing <>", value, "healthInsurRateNoNursing");
            return (Criteria) this;
        }

        public Criteria andHealthInsurRateNoNursingGreaterThan(BigDecimal value) {
            addCriterion("health_insur_rate_no_nursing >", value, "healthInsurRateNoNursing");
            return (Criteria) this;
        }

        public Criteria andHealthInsurRateNoNursingGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("health_insur_rate_no_nursing >=", value, "healthInsurRateNoNursing");
            return (Criteria) this;
        }

        public Criteria andHealthInsurRateNoNursingLessThan(BigDecimal value) {
            addCriterion("health_insur_rate_no_nursing <", value, "healthInsurRateNoNursing");
            return (Criteria) this;
        }

        public Criteria andHealthInsurRateNoNursingLessThanOrEqualTo(BigDecimal value) {
            addCriterion("health_insur_rate_no_nursing <=", value, "healthInsurRateNoNursing");
            return (Criteria) this;
        }

        public Criteria andHealthInsurRateNoNursingIn(List<BigDecimal> values) {
            addCriterion("health_insur_rate_no_nursing in", values, "healthInsurRateNoNursing");
            return (Criteria) this;
        }

        public Criteria andHealthInsurRateNoNursingNotIn(List<BigDecimal> values) {
            addCriterion("health_insur_rate_no_nursing not in", values, "healthInsurRateNoNursing");
            return (Criteria) this;
        }

        public Criteria andHealthInsurRateNoNursingBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("health_insur_rate_no_nursing between", value1, value2, "healthInsurRateNoNursing");
            return (Criteria) this;
        }

        public Criteria andHealthInsurRateNoNursingNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("health_insur_rate_no_nursing not between", value1, value2, "healthInsurRateNoNursing");
            return (Criteria) this;
        }

        public Criteria andHealthInsurRateWithNursingIsNull() {
            addCriterion("health_insur_rate_with_nursing is null");
            return (Criteria) this;
        }

        public Criteria andHealthInsurRateWithNursingIsNotNull() {
            addCriterion("health_insur_rate_with_nursing is not null");
            return (Criteria) this;
        }

        public Criteria andHealthInsurRateWithNursingEqualTo(BigDecimal value) {
            addCriterion("health_insur_rate_with_nursing =", value, "healthInsurRateWithNursing");
            return (Criteria) this;
        }

        public Criteria andHealthInsurRateWithNursingNotEqualTo(BigDecimal value) {
            addCriterion("health_insur_rate_with_nursing <>", value, "healthInsurRateWithNursing");
            return (Criteria) this;
        }

        public Criteria andHealthInsurRateWithNursingGreaterThan(BigDecimal value) {
            addCriterion("health_insur_rate_with_nursing >", value, "healthInsurRateWithNursing");
            return (Criteria) this;
        }

        public Criteria andHealthInsurRateWithNursingGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("health_insur_rate_with_nursing >=", value, "healthInsurRateWithNursing");
            return (Criteria) this;
        }

        public Criteria andHealthInsurRateWithNursingLessThan(BigDecimal value) {
            addCriterion("health_insur_rate_with_nursing <", value, "healthInsurRateWithNursing");
            return (Criteria) this;
        }

        public Criteria andHealthInsurRateWithNursingLessThanOrEqualTo(BigDecimal value) {
            addCriterion("health_insur_rate_with_nursing <=", value, "healthInsurRateWithNursing");
            return (Criteria) this;
        }

        public Criteria andHealthInsurRateWithNursingIn(List<BigDecimal> values) {
            addCriterion("health_insur_rate_with_nursing in", values, "healthInsurRateWithNursing");
            return (Criteria) this;
        }

        public Criteria andHealthInsurRateWithNursingNotIn(List<BigDecimal> values) {
            addCriterion("health_insur_rate_with_nursing not in", values, "healthInsurRateWithNursing");
            return (Criteria) this;
        }

        public Criteria andHealthInsurRateWithNursingBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("health_insur_rate_with_nursing between", value1, value2, "healthInsurRateWithNursing");
            return (Criteria) this;
        }

        public Criteria andHealthInsurRateWithNursingNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("health_insur_rate_with_nursing not between", value1, value2, "healthInsurRateWithNursing");
            return (Criteria) this;
        }

        public Criteria andHealthRoundingIsNull() {
            addCriterion("health_rounding is null");
            return (Criteria) this;
        }

        public Criteria andHealthRoundingIsNotNull() {
            addCriterion("health_rounding is not null");
            return (Criteria) this;
        }

        public Criteria andHealthRoundingEqualTo(Integer value) {
            addCriterion("health_rounding =", value, "healthRounding");
            return (Criteria) this;
        }

        public Criteria andHealthRoundingNotEqualTo(Integer value) {
            addCriterion("health_rounding <>", value, "healthRounding");
            return (Criteria) this;
        }

        public Criteria andHealthRoundingGreaterThan(Integer value) {
            addCriterion("health_rounding >", value, "healthRounding");
            return (Criteria) this;
        }

        public Criteria andHealthRoundingGreaterThanOrEqualTo(Integer value) {
            addCriterion("health_rounding >=", value, "healthRounding");
            return (Criteria) this;
        }

        public Criteria andHealthRoundingLessThan(Integer value) {
            addCriterion("health_rounding <", value, "healthRounding");
            return (Criteria) this;
        }

        public Criteria andHealthRoundingLessThanOrEqualTo(Integer value) {
            addCriterion("health_rounding <=", value, "healthRounding");
            return (Criteria) this;
        }

        public Criteria andHealthRoundingIn(List<Integer> values) {
            addCriterion("health_rounding in", values, "healthRounding");
            return (Criteria) this;
        }

        public Criteria andHealthRoundingNotIn(List<Integer> values) {
            addCriterion("health_rounding not in", values, "healthRounding");
            return (Criteria) this;
        }

        public Criteria andHealthRoundingBetween(Integer value1, Integer value2) {
            addCriterion("health_rounding between", value1, value2, "healthRounding");
            return (Criteria) this;
        }

        public Criteria andHealthRoundingNotBetween(Integer value1, Integer value2) {
            addCriterion("health_rounding not between", value1, value2, "healthRounding");
            return (Criteria) this;
        }

        public Criteria andWelfareInsuranceRateIsNull() {
            addCriterion("welfare_insurance_rate is null");
            return (Criteria) this;
        }

        public Criteria andWelfareInsuranceRateIsNotNull() {
            addCriterion("welfare_insurance_rate is not null");
            return (Criteria) this;
        }

        public Criteria andWelfareInsuranceRateEqualTo(BigDecimal value) {
            addCriterion("welfare_insurance_rate =", value, "welfareInsuranceRate");
            return (Criteria) this;
        }

        public Criteria andWelfareInsuranceRateNotEqualTo(BigDecimal value) {
            addCriterion("welfare_insurance_rate <>", value, "welfareInsuranceRate");
            return (Criteria) this;
        }

        public Criteria andWelfareInsuranceRateGreaterThan(BigDecimal value) {
            addCriterion("welfare_insurance_rate >", value, "welfareInsuranceRate");
            return (Criteria) this;
        }

        public Criteria andWelfareInsuranceRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("welfare_insurance_rate >=", value, "welfareInsuranceRate");
            return (Criteria) this;
        }

        public Criteria andWelfareInsuranceRateLessThan(BigDecimal value) {
            addCriterion("welfare_insurance_rate <", value, "welfareInsuranceRate");
            return (Criteria) this;
        }

        public Criteria andWelfareInsuranceRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("welfare_insurance_rate <=", value, "welfareInsuranceRate");
            return (Criteria) this;
        }

        public Criteria andWelfareInsuranceRateIn(List<BigDecimal> values) {
            addCriterion("welfare_insurance_rate in", values, "welfareInsuranceRate");
            return (Criteria) this;
        }

        public Criteria andWelfareInsuranceRateNotIn(List<BigDecimal> values) {
            addCriterion("welfare_insurance_rate not in", values, "welfareInsuranceRate");
            return (Criteria) this;
        }

        public Criteria andWelfareInsuranceRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("welfare_insurance_rate between", value1, value2, "welfareInsuranceRate");
            return (Criteria) this;
        }

        public Criteria andWelfareInsuranceRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("welfare_insurance_rate not between", value1, value2, "welfareInsuranceRate");
            return (Criteria) this;
        }

        public Criteria andWelfareRoundingIsNull() {
            addCriterion("welfare_rounding is null");
            return (Criteria) this;
        }

        public Criteria andWelfareRoundingIsNotNull() {
            addCriterion("welfare_rounding is not null");
            return (Criteria) this;
        }

        public Criteria andWelfareRoundingEqualTo(Integer value) {
            addCriterion("welfare_rounding =", value, "welfareRounding");
            return (Criteria) this;
        }

        public Criteria andWelfareRoundingNotEqualTo(Integer value) {
            addCriterion("welfare_rounding <>", value, "welfareRounding");
            return (Criteria) this;
        }

        public Criteria andWelfareRoundingGreaterThan(Integer value) {
            addCriterion("welfare_rounding >", value, "welfareRounding");
            return (Criteria) this;
        }

        public Criteria andWelfareRoundingGreaterThanOrEqualTo(Integer value) {
            addCriterion("welfare_rounding >=", value, "welfareRounding");
            return (Criteria) this;
        }

        public Criteria andWelfareRoundingLessThan(Integer value) {
            addCriterion("welfare_rounding <", value, "welfareRounding");
            return (Criteria) this;
        }

        public Criteria andWelfareRoundingLessThanOrEqualTo(Integer value) {
            addCriterion("welfare_rounding <=", value, "welfareRounding");
            return (Criteria) this;
        }

        public Criteria andWelfareRoundingIn(List<Integer> values) {
            addCriterion("welfare_rounding in", values, "welfareRounding");
            return (Criteria) this;
        }

        public Criteria andWelfareRoundingNotIn(List<Integer> values) {
            addCriterion("welfare_rounding not in", values, "welfareRounding");
            return (Criteria) this;
        }

        public Criteria andWelfareRoundingBetween(Integer value1, Integer value2) {
            addCriterion("welfare_rounding between", value1, value2, "welfareRounding");
            return (Criteria) this;
        }

        public Criteria andWelfareRoundingNotBetween(Integer value1, Integer value2) {
            addCriterion("welfare_rounding not between", value1, value2, "welfareRounding");
            return (Criteria) this;
        }

        public Criteria andWelfareExceptionRateIsNull() {
            addCriterion("welfare_exception_rate is null");
            return (Criteria) this;
        }

        public Criteria andWelfareExceptionRateIsNotNull() {
            addCriterion("welfare_exception_rate is not null");
            return (Criteria) this;
        }

        public Criteria andWelfareExceptionRateEqualTo(BigDecimal value) {
            addCriterion("welfare_exception_rate =", value, "welfareExceptionRate");
            return (Criteria) this;
        }

        public Criteria andWelfareExceptionRateNotEqualTo(BigDecimal value) {
            addCriterion("welfare_exception_rate <>", value, "welfareExceptionRate");
            return (Criteria) this;
        }

        public Criteria andWelfareExceptionRateGreaterThan(BigDecimal value) {
            addCriterion("welfare_exception_rate >", value, "welfareExceptionRate");
            return (Criteria) this;
        }

        public Criteria andWelfareExceptionRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("welfare_exception_rate >=", value, "welfareExceptionRate");
            return (Criteria) this;
        }

        public Criteria andWelfareExceptionRateLessThan(BigDecimal value) {
            addCriterion("welfare_exception_rate <", value, "welfareExceptionRate");
            return (Criteria) this;
        }

        public Criteria andWelfareExceptionRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("welfare_exception_rate <=", value, "welfareExceptionRate");
            return (Criteria) this;
        }

        public Criteria andWelfareExceptionRateIn(List<BigDecimal> values) {
            addCriterion("welfare_exception_rate in", values, "welfareExceptionRate");
            return (Criteria) this;
        }

        public Criteria andWelfareExceptionRateNotIn(List<BigDecimal> values) {
            addCriterion("welfare_exception_rate not in", values, "welfareExceptionRate");
            return (Criteria) this;
        }

        public Criteria andWelfareExceptionRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("welfare_exception_rate between", value1, value2, "welfareExceptionRate");
            return (Criteria) this;
        }

        public Criteria andWelfareExceptionRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("welfare_exception_rate not between", value1, value2, "welfareExceptionRate");
            return (Criteria) this;
        }

        public Criteria andWelfareAdditionRateIsNull() {
            addCriterion("welfare_addition_rate is null");
            return (Criteria) this;
        }

        public Criteria andWelfareAdditionRateIsNotNull() {
            addCriterion("welfare_addition_rate is not null");
            return (Criteria) this;
        }

        public Criteria andWelfareAdditionRateEqualTo(BigDecimal value) {
            addCriterion("welfare_addition_rate =", value, "welfareAdditionRate");
            return (Criteria) this;
        }

        public Criteria andWelfareAdditionRateNotEqualTo(BigDecimal value) {
            addCriterion("welfare_addition_rate <>", value, "welfareAdditionRate");
            return (Criteria) this;
        }

        public Criteria andWelfareAdditionRateGreaterThan(BigDecimal value) {
            addCriterion("welfare_addition_rate >", value, "welfareAdditionRate");
            return (Criteria) this;
        }

        public Criteria andWelfareAdditionRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("welfare_addition_rate >=", value, "welfareAdditionRate");
            return (Criteria) this;
        }

        public Criteria andWelfareAdditionRateLessThan(BigDecimal value) {
            addCriterion("welfare_addition_rate <", value, "welfareAdditionRate");
            return (Criteria) this;
        }

        public Criteria andWelfareAdditionRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("welfare_addition_rate <=", value, "welfareAdditionRate");
            return (Criteria) this;
        }

        public Criteria andWelfareAdditionRateIn(List<BigDecimal> values) {
            addCriterion("welfare_addition_rate in", values, "welfareAdditionRate");
            return (Criteria) this;
        }

        public Criteria andWelfareAdditionRateNotIn(List<BigDecimal> values) {
            addCriterion("welfare_addition_rate not in", values, "welfareAdditionRate");
            return (Criteria) this;
        }

        public Criteria andWelfareAdditionRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("welfare_addition_rate between", value1, value2, "welfareAdditionRate");
            return (Criteria) this;
        }

        public Criteria andWelfareAdditionRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("welfare_addition_rate not between", value1, value2, "welfareAdditionRate");
            return (Criteria) this;
        }

        public Criteria andWelfareAdditionRationIsNull() {
            addCriterion("welfare_addition_ration is null");
            return (Criteria) this;
        }

        public Criteria andWelfareAdditionRationIsNotNull() {
            addCriterion("welfare_addition_ration is not null");
            return (Criteria) this;
        }

        public Criteria andWelfareAdditionRationEqualTo(Integer value) {
            addCriterion("welfare_addition_ration =", value, "welfareAdditionRation");
            return (Criteria) this;
        }

        public Criteria andWelfareAdditionRationNotEqualTo(Integer value) {
            addCriterion("welfare_addition_ration <>", value, "welfareAdditionRation");
            return (Criteria) this;
        }

        public Criteria andWelfareAdditionRationGreaterThan(Integer value) {
            addCriterion("welfare_addition_ration >", value, "welfareAdditionRation");
            return (Criteria) this;
        }

        public Criteria andWelfareAdditionRationGreaterThanOrEqualTo(Integer value) {
            addCriterion("welfare_addition_ration >=", value, "welfareAdditionRation");
            return (Criteria) this;
        }

        public Criteria andWelfareAdditionRationLessThan(Integer value) {
            addCriterion("welfare_addition_ration <", value, "welfareAdditionRation");
            return (Criteria) this;
        }

        public Criteria andWelfareAdditionRationLessThanOrEqualTo(Integer value) {
            addCriterion("welfare_addition_ration <=", value, "welfareAdditionRation");
            return (Criteria) this;
        }

        public Criteria andWelfareAdditionRationIn(List<Integer> values) {
            addCriterion("welfare_addition_ration in", values, "welfareAdditionRation");
            return (Criteria) this;
        }

        public Criteria andWelfareAdditionRationNotIn(List<Integer> values) {
            addCriterion("welfare_addition_ration not in", values, "welfareAdditionRation");
            return (Criteria) this;
        }

        public Criteria andWelfareAdditionRationBetween(Integer value1, Integer value2) {
            addCriterion("welfare_addition_ration between", value1, value2, "welfareAdditionRation");
            return (Criteria) this;
        }

        public Criteria andWelfareAdditionRationNotBetween(Integer value1, Integer value2) {
            addCriterion("welfare_addition_ration not between", value1, value2, "welfareAdditionRation");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.t_insurance
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.t_insurance
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}