package jp.co.aliber.accsystem.mapper.auto;

import java.util.List;
import jp.co.aliber.accsystem.entity.auto.CalculationPrice;
import jp.co.aliber.accsystem.entity.auto.CalculationPriceExample;
import org.apache.ibatis.annotations.Param;

public interface CalculationPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.calculation_price
     *
     * @mbg.generated
     */
    long countByExample(CalculationPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.calculation_price
     *
     * @mbg.generated
     */
    int deleteByExample(CalculationPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.calculation_price
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long calculationPriceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.calculation_price
     *
     * @mbg.generated
     */
    int insert(CalculationPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.calculation_price
     *
     * @mbg.generated
     */
    int insertSelective(CalculationPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.calculation_price
     *
     * @mbg.generated
     */
    List<CalculationPrice> selectByExample(CalculationPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.calculation_price
     *
     * @mbg.generated
     */
    CalculationPrice selectByPrimaryKey(Long calculationPriceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.calculation_price
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CalculationPrice record, @Param("example") CalculationPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.calculation_price
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CalculationPrice record, @Param("example") CalculationPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.calculation_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CalculationPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.calculation_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CalculationPrice record);
}