package jp.co.aliber.accsystem.mapper.auto;

import java.util.List;
import jp.co.aliber.accsystem.entity.auto.FixedDeduction;
import jp.co.aliber.accsystem.entity.auto.FixedDeductionExample;
import org.apache.ibatis.annotations.Param;

public interface FixedDeductionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fixed_deduction
     *
     * @mbg.generated
     */
    long countByExample(FixedDeductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fixed_deduction
     *
     * @mbg.generated
     */
    int deleteByExample(FixedDeductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fixed_deduction
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long fixedDeductionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fixed_deduction
     *
     * @mbg.generated
     */
    int insert(FixedDeduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fixed_deduction
     *
     * @mbg.generated
     */
    int insertSelective(FixedDeduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fixed_deduction
     *
     * @mbg.generated
     */
    List<FixedDeduction> selectByExample(FixedDeductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fixed_deduction
     *
     * @mbg.generated
     */
    FixedDeduction selectByPrimaryKey(Long fixedDeductionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fixed_deduction
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FixedDeduction record, @Param("example") FixedDeductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fixed_deduction
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FixedDeduction record, @Param("example") FixedDeductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fixed_deduction
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FixedDeduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fixed_deduction
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FixedDeduction record);
}