package jp.co.aliber.accsystem.mapper.auto;

import java.util.List;
import jp.co.aliber.accsystem.entity.auto.FixedPayment;
import jp.co.aliber.accsystem.entity.auto.FixedPaymentExample;
import org.apache.ibatis.annotations.Param;

public interface FixedPaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fixed_payment
     *
     * @mbg.generated
     */
    long countByExample(FixedPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fixed_payment
     *
     * @mbg.generated
     */
    int deleteByExample(FixedPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fixed_payment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long fixedPaymentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fixed_payment
     *
     * @mbg.generated
     */
    int insert(FixedPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fixed_payment
     *
     * @mbg.generated
     */
    int insertSelective(FixedPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fixed_payment
     *
     * @mbg.generated
     */
    List<FixedPayment> selectByExample(FixedPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fixed_payment
     *
     * @mbg.generated
     */
    FixedPayment selectByPrimaryKey(Long fixedPaymentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fixed_payment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FixedPayment record, @Param("example") FixedPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fixed_payment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FixedPayment record, @Param("example") FixedPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fixed_payment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FixedPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fixed_payment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FixedPayment record);
}