package jp.co.aliber.accsystem.mapper.auto;

import java.util.List;
import jp.co.aliber.accsystem.entity.auto.LList;
import jp.co.aliber.accsystem.entity.auto.LListExample;
import org.apache.ibatis.annotations.Param;

public interface LListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.l_list
     *
     * @mbg.generated
     */
    long countByExample(LListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.l_list
     *
     * @mbg.generated
     */
    int deleteByExample(LListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.l_list
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("literalClassId") Integer literalClassId, @Param("literalId") Integer literalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.l_list
     *
     * @mbg.generated
     */
    int insert(LList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.l_list
     *
     * @mbg.generated
     */
    int insertSelective(LList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.l_list
     *
     * @mbg.generated
     */
    List<LList> selectByExample(LListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.l_list
     *
     * @mbg.generated
     */
    LList selectByPrimaryKey(@Param("literalClassId") Integer literalClassId, @Param("literalId") Integer literalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.l_list
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LList record, @Param("example") LListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.l_list
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LList record, @Param("example") LListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.l_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.l_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LList record);
}