package jp.co.aliber.accsystem.mapper.auto;

import java.util.List;
import jp.co.aliber.accsystem.entity.auto.MStandardReward;
import jp.co.aliber.accsystem.entity.auto.MStandardRewardExample;
import org.apache.ibatis.annotations.Param;

public interface MStandardRewardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_standard_reward
     *
     * @mbg.generated
     */
    long countByExample(MStandardRewardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_standard_reward
     *
     * @mbg.generated
     */
    int deleteByExample(MStandardRewardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_standard_reward
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer managementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_standard_reward
     *
     * @mbg.generated
     */
    int insert(MStandardReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_standard_reward
     *
     * @mbg.generated
     */
    int insertSelective(MStandardReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_standard_reward
     *
     * @mbg.generated
     */
    List<MStandardReward> selectByExample(MStandardRewardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_standard_reward
     *
     * @mbg.generated
     */
    MStandardReward selectByPrimaryKey(Integer managementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_standard_reward
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MStandardReward record, @Param("example") MStandardRewardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_standard_reward
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MStandardReward record, @Param("example") MStandardRewardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_standard_reward
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MStandardReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_standard_reward
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MStandardReward record);
}