package jp.co.aliber.accsystem.mapper.auto;

import java.util.List;
import jp.co.aliber.accsystem.entity.auto.MWelfareInsuranceStandardPayment;
import jp.co.aliber.accsystem.entity.auto.MWelfareInsuranceStandardPaymentExample;
import org.apache.ibatis.annotations.Param;

public interface MWelfareInsuranceStandardPaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_welfare_insurance_standard_payment
     *
     * @mbg.generated
     */
    long countByExample(MWelfareInsuranceStandardPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_welfare_insurance_standard_payment
     *
     * @mbg.generated
     */
    int deleteByExample(MWelfareInsuranceStandardPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_welfare_insurance_standard_payment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("paymentStart") Long paymentStart, @Param("paymentEnd") Long paymentEnd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_welfare_insurance_standard_payment
     *
     * @mbg.generated
     */
    int insert(MWelfareInsuranceStandardPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_welfare_insurance_standard_payment
     *
     * @mbg.generated
     */
    int insertSelective(MWelfareInsuranceStandardPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_welfare_insurance_standard_payment
     *
     * @mbg.generated
     */
    List<MWelfareInsuranceStandardPayment> selectByExample(MWelfareInsuranceStandardPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_welfare_insurance_standard_payment
     *
     * @mbg.generated
     */
    MWelfareInsuranceStandardPayment selectByPrimaryKey(@Param("paymentStart") Long paymentStart, @Param("paymentEnd") Long paymentEnd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_welfare_insurance_standard_payment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MWelfareInsuranceStandardPayment record, @Param("example") MWelfareInsuranceStandardPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_welfare_insurance_standard_payment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MWelfareInsuranceStandardPayment record, @Param("example") MWelfareInsuranceStandardPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_welfare_insurance_standard_payment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MWelfareInsuranceStandardPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.m_welfare_insurance_standard_payment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MWelfareInsuranceStandardPayment record);
}