package jp.co.aliber.accsystem.mapper.auto;

import java.util.List;
import jp.co.aliber.accsystem.entity.auto.OvertimeWork;
import jp.co.aliber.accsystem.entity.auto.OvertimeWorkExample;
import org.apache.ibatis.annotations.Param;

public interface OvertimeWorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.overtime_work
     *
     * @mbg.generated
     */
    long countByExample(OvertimeWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.overtime_work
     *
     * @mbg.generated
     */
    int deleteByExample(OvertimeWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.overtime_work
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long overtimeWorkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.overtime_work
     *
     * @mbg.generated
     */
    int insert(OvertimeWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.overtime_work
     *
     * @mbg.generated
     */
    int insertSelective(OvertimeWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.overtime_work
     *
     * @mbg.generated
     */
    List<OvertimeWork> selectByExample(OvertimeWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.overtime_work
     *
     * @mbg.generated
     */
    OvertimeWork selectByPrimaryKey(Long overtimeWorkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.overtime_work
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OvertimeWork record, @Param("example") OvertimeWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.overtime_work
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OvertimeWork record, @Param("example") OvertimeWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.overtime_work
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OvertimeWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.overtime_work
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OvertimeWork record);
}