package jp.co.aliber.accsystem.mapper.auto;

import java.util.List;
import jp.co.aliber.accsystem.entity.auto.PayDetailsInput;
import jp.co.aliber.accsystem.entity.auto.PayDetailsInputExample;
import org.apache.ibatis.annotations.Param;

public interface PayDetailsInputMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pay_details_input
     *
     * @mbg.generated
     */
    long countByExample(PayDetailsInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pay_details_input
     *
     * @mbg.generated
     */
    int deleteByExample(PayDetailsInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pay_details_input
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long payDetailsInputId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pay_details_input
     *
     * @mbg.generated
     */
    int insert(PayDetailsInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pay_details_input
     *
     * @mbg.generated
     */
    int insertSelective(PayDetailsInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pay_details_input
     *
     * @mbg.generated
     */
    List<PayDetailsInput> selectByExample(PayDetailsInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pay_details_input
     *
     * @mbg.generated
     */
    PayDetailsInput selectByPrimaryKey(Long payDetailsInputId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pay_details_input
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PayDetailsInput record, @Param("example") PayDetailsInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pay_details_input
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PayDetailsInput record, @Param("example") PayDetailsInputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pay_details_input
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PayDetailsInput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.pay_details_input
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PayDetailsInput record);
}