package jp.co.aliber.accsystem.mapper.auto;

import java.util.List;
import jp.co.aliber.accsystem.entity.auto.TCompanyDepartment;
import jp.co.aliber.accsystem.entity.auto.TCompanyDepartmentExample;
import org.apache.ibatis.annotations.Param;

public interface TCompanyDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_company_department
     *
     * @mbg.generated
     */
    long countByExample(TCompanyDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_company_department
     *
     * @mbg.generated
     */
    int deleteByExample(TCompanyDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_company_department
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("deptId") Integer deptId, @Param("compId") Integer compId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_company_department
     *
     * @mbg.generated
     */
    int insert(TCompanyDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_company_department
     *
     * @mbg.generated
     */
    int insertSelective(TCompanyDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_company_department
     *
     * @mbg.generated
     */
    List<TCompanyDepartment> selectByExample(TCompanyDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_company_department
     *
     * @mbg.generated
     */
    TCompanyDepartment selectByPrimaryKey(@Param("deptId") Integer deptId, @Param("compId") Integer compId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_company_department
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCompanyDepartment record, @Param("example") TCompanyDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_company_department
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCompanyDepartment record, @Param("example") TCompanyDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_company_department
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCompanyDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_company_department
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCompanyDepartment record);
}