package jp.co.aliber.accsystem.mapper.auto;

import java.util.List;
import jp.co.aliber.accsystem.entity.auto.TCompany;
import jp.co.aliber.accsystem.entity.auto.TCompanyExample;
import org.apache.ibatis.annotations.Param;

public interface TCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_company
     *
     * @mbg.generated
     */
    long countByExample(TCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_company
     *
     * @mbg.generated
     */
    int deleteByExample(TCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_company
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer compId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_company
     *
     * @mbg.generated
     */
    int insert(TCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_company
     *
     * @mbg.generated
     */
    int insertSelective(TCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_company
     *
     * @mbg.generated
     */
    List<TCompany> selectByExample(TCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_company
     *
     * @mbg.generated
     */
    TCompany selectByPrimaryKey(Integer compId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_company
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCompany record, @Param("example") TCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_company
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCompany record, @Param("example") TCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCompany record);
}