package jp.co.aliber.accsystem.mapper.auto;

import java.util.List;
import jp.co.aliber.accsystem.entity.auto.TEmployeeFixedPayment;
import jp.co.aliber.accsystem.entity.auto.TEmployeeFixedPaymentExample;
import org.apache.ibatis.annotations.Param;

public interface TEmployeeFixedPaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_fixed_payment
     *
     * @mbg.generated
     */
    long countByExample(TEmployeeFixedPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_fixed_payment
     *
     * @mbg.generated
     */
    int deleteByExample(TEmployeeFixedPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_fixed_payment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("employeeId") Integer employeeId, @Param("compId") Integer compId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_fixed_payment
     *
     * @mbg.generated
     */
    int insert(TEmployeeFixedPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_fixed_payment
     *
     * @mbg.generated
     */
    int insertSelective(TEmployeeFixedPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_fixed_payment
     *
     * @mbg.generated
     */
    List<TEmployeeFixedPayment> selectByExample(TEmployeeFixedPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_fixed_payment
     *
     * @mbg.generated
     */
    TEmployeeFixedPayment selectByPrimaryKey(@Param("employeeId") Integer employeeId, @Param("compId") Integer compId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_fixed_payment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TEmployeeFixedPayment record, @Param("example") TEmployeeFixedPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_fixed_payment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TEmployeeFixedPayment record, @Param("example") TEmployeeFixedPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_fixed_payment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TEmployeeFixedPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_fixed_payment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TEmployeeFixedPayment record);
}