package jp.co.aliber.accsystem.mapper.auto;

import java.util.List;
import jp.co.aliber.accsystem.entity.auto.TEmployeeFixedDeduction;
import jp.co.aliber.accsystem.entity.auto.TEmployeeFixedDeductionExample;
import org.apache.ibatis.annotations.Param;

public interface TEmployeeFixedDeductionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_fixed_deduction
     *
     * @mbg.generated
     */
    long countByExample(TEmployeeFixedDeductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_fixed_deduction
     *
     * @mbg.generated
     */
    int deleteByExample(TEmployeeFixedDeductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_fixed_deduction
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("employeeId") Integer employeeId, @Param("compId") Integer compId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_fixed_deduction
     *
     * @mbg.generated
     */
    int insert(TEmployeeFixedDeduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_fixed_deduction
     *
     * @mbg.generated
     */
    int insertSelective(TEmployeeFixedDeduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_fixed_deduction
     *
     * @mbg.generated
     */
    List<TEmployeeFixedDeduction> selectByExample(TEmployeeFixedDeductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_fixed_deduction
     *
     * @mbg.generated
     */
    TEmployeeFixedDeduction selectByPrimaryKey(@Param("employeeId") Integer employeeId, @Param("compId") Integer compId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_fixed_deduction
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TEmployeeFixedDeduction record, @Param("example") TEmployeeFixedDeductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_fixed_deduction
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TEmployeeFixedDeduction record, @Param("example") TEmployeeFixedDeductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_fixed_deduction
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TEmployeeFixedDeduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_fixed_deduction
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TEmployeeFixedDeduction record);
}