package jp.co.aliber.accsystem.mapper.auto;

import java.util.List;
import jp.co.aliber.accsystem.entity.auto.TEmployeeBankAccount;
import jp.co.aliber.accsystem.entity.auto.TEmployeeBankAccountExample;
import org.apache.ibatis.annotations.Param;

public interface TEmployeeBankAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_bank_account
     *
     * @mbg.generated
     */
    long countByExample(TEmployeeBankAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_bank_account
     *
     * @mbg.generated
     */
    int deleteByExample(TEmployeeBankAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_bank_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("employeeId") Integer employeeId, @Param("compId") Integer compId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_bank_account
     *
     * @mbg.generated
     */
    int insert(TEmployeeBankAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_bank_account
     *
     * @mbg.generated
     */
    int insertSelective(TEmployeeBankAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_bank_account
     *
     * @mbg.generated
     */
    List<TEmployeeBankAccount> selectByExample(TEmployeeBankAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_bank_account
     *
     * @mbg.generated
     */
    TEmployeeBankAccount selectByPrimaryKey(@Param("employeeId") Integer employeeId, @Param("compId") Integer compId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_bank_account
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TEmployeeBankAccount record, @Param("example") TEmployeeBankAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_bank_account
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TEmployeeBankAccount record, @Param("example") TEmployeeBankAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_bank_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TEmployeeBankAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_employee_bank_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TEmployeeBankAccount record);
}