package jp.co.aliber.accsystem.mapper.auto;

import java.util.List;
import jp.co.aliber.accsystem.entity.auto.TLoginUser;
import jp.co.aliber.accsystem.entity.auto.TLoginUserExample;
import org.apache.ibatis.annotations.Param;

public interface TLoginUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_login_user
     *
     * @mbg.generated
     */
    long countByExample(TLoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_login_user
     *
     * @mbg.generated
     */
    int deleteByExample(TLoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_login_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_login_user
     *
     * @mbg.generated
     */
    int insert(TLoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_login_user
     *
     * @mbg.generated
     */
    int insertSelective(TLoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_login_user
     *
     * @mbg.generated
     */
    List<TLoginUser> selectByExample(TLoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_login_user
     *
     * @mbg.generated
     */
    TLoginUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_login_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TLoginUser record, @Param("example") TLoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_login_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TLoginUser record, @Param("example") TLoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_login_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TLoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_login_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TLoginUser record);
}